import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Every post's metadata, regenerated by scripts/sync-articles.js earlier in the
// same `npm run build` chain (see package.json), so it's always in sync with
// content/. Same source prerender.mjs derives its route list from, so the
// sitemap can't list a URL that wasn't prerendered (or vice versa).
const mdxMeta = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/mdx-meta.json'), 'utf8')
);

// Generated by scripts/generate-beastlypedia-index.js, and read by prerender.mjs
// from the same file - so the sitemap cannot list a Beastfile that was never
// prerendered, which is exactly the drift the hand-mirrored lists below invite.
const beastlypedia = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/beastlypedia-index.json'), 'utf8')
);

// The legal matrix, read by prerender.mjs from this same file, for the same
// reason as the two above: a hand-copied species list goes stale the moment a
// new animal is researched, and then the page exists but is never indexed.
const legalStatus = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/data/legalStatus.json'), 'utf8')
);

function parseFrontmatter(content) {
  // \r? - MDX files in this repo are a mix of LF and CRLF line endings;
  // an LF-only match silently drops frontmatter and the slug falls back
  // to the filename, putting wrong URLs in the sitemap.
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const result = {};
  for (const line of match[1].split(/\r?\n/)) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    const val = line.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, '');
    result[key] = val;
  }
  return result;
}

// Mirrors slugify in src/lib/utils/slugify.js (incl. the "&"/"and" rule that
// makes "Small & Exotic Pets" produce "small-and-exotic-pets").
const slugifyCategory = (text) => text.toString().toLowerCase()
  .replace(/\s*&\s*|\s+and\s+/g, '-and-')
  .replace(/\s+/g, '-')
  .replace(/[^a-z0-9-]/g, '')
  .replace(/-+/g, '-')
  .replace(/^-|-$/g, '');

// Blog category slugs, one per category that actually has at least one post -
// Blog.jsx renders a pill for each of those and prerender.mjs prerenders them
// (see getMdxCategoryRoutes there), so they belong in the sitemap too.
// Excludes the two retired ones that 301 away (site-news, short-stories).
function getCategorySlugs() {
  const slugs = new Set();
  for (const post of mdxMeta) {
    // All categories the post is filed under, not just the primary one.
    const cats = (post.categories?.length ? post.categories : [post.category]).filter(Boolean);
    for (const cat of cats) {
      const slug = slugifyCategory(cat);
      if (!slug || slug === 'site-news' || slug === 'short-stories') continue;
      slugs.add(slug);
    }
  }
  return [...slugs];
}

// Chronicles series slug prefixes (mirrors CHRONICLES_SERIES in src/lib/chronicles.js).
// Their stories live at /chronicles/<id>/<part>/, not /blog/<slug>/.
const chroniclesPrefixes = { dex: 'chronicles-of-dex', otis: 'chronicles-of-otis' };
const isChroniclesSlug = (slug) =>
  Object.values(chroniclesPrefixes).some(prefix => slug.startsWith(prefix));

// mdx-meta.json carries the publish date but not `lastUpdated`, and lastmod
// should reflect the newer of the two when a post has been revised, so read it
// back out of the source file's frontmatter (post.path is repo-relative, e.g.
// "/content/guides/koi-cost-guide.mdx").
function readLastUpdated(post) {
  const filePath = path.join(__dirname, post.path);
  if (!fs.existsSync(filePath)) return null;
  return parseFrontmatter(fs.readFileSync(filePath, 'utf8')).lastUpdated || null;
}

// A post's date can be set ahead as a release date (see hasReachedPublishDate in
// public/_worker.js). The page itself stays in the sitemap either way, since it is
// deployed and we want it crawled, but a <lastmod> in the future is a bad signal:
// it claims the page changed on a day that has not happened. Drop it until then.
const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
const notInFuture = (date) => (date && String(date).slice(0, 10) <= today ? date : null);

function getMdxPosts() {
  // Short stories live on /chronicles/, not /blog/ (old URLs 301 in _redirects)
  return mdxMeta.filter(post => !isChroniclesSlug(post.slug)).map(post => ({
    path: `/blog/${post.slug}/`,
    // Only emit lastmod when the frontmatter carries a real, already-reached date - a
    // fabricated build-date lastmod is worse than none at all, and so is a future one.
    lastmod: notInFuture(readLastUpdated(post)) || notInFuture(post.date) || null,
    changefreq: 'weekly',
    priority: '0.7',
  }));
}

// /chronicles/<series>/ (landing list) + /chronicles/<series>/<n>/ per part.
// Part counts = the MDX short-story posts per series.
function getChroniclesPages() {
  const dedupedSlugs = [...new Set(mdxMeta.map(post => post.slug).filter(isChroniclesSlug))];

  const pages = [];
  for (const [id, prefix] of Object.entries(chroniclesPrefixes)) {
    const partCount = dedupedSlugs.filter(s => s.startsWith(prefix)).length;
    pages.push({ path: `/chronicles/${id}/`, changefreq: 'weekly', priority: '0.7' });
    for (let n = 1; n <= partCount; n++) {
      pages.push({ path: `/chronicles/${id}/${n}/`, changefreq: 'weekly', priority: '0.7' });
    }
  }
  return pages;
}

const BASE_URL = 'https://beastlyfacts.com';

// Encyclopedia category slugs (mirrors encyclopediaCategories in encyclopedia.js)
const encyclopediaCategories = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Guide filter slugs (mirrors guideFilters in Encyclopedia.jsx, excluding 'all')
const guideFilters = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Fun-facts category slugs (mirrors `categories` in src/lib/data/facts.js, slugified)
const factCategories = [
  'birds', 'dogs-and-cats', 'mammals', 'ocean', 'reptiles', 'weird-and-wonderful',
];

// Gear pet-type filter slugs (mirrors GEAR_PET_TYPES in src/lib/data/affiliateProducts.js)
const gearPetTypes = [
  'reptiles-amphibians', 'birds', 'fish', 'dogs-cats', 'small-mammals',
];

const staticPages = [
  '/',
  '/about/',
  '/contact/',
  '/categories/',
  '/facts/',
  '/animal-facts/',
  '/fact-files/',
  '/gallery/',
  '/blog/',
  '/encyclopedia/',
  '/beastlypedia/',
  '/guides/',
  '/gear/',
  '/quiz/personality/',
  '/quiz/trivia/',
  '/quiz/knowledge/',
  '/glossary/',
  '/exotic-pet-laws/',

  // One page per animal in the legal matrix. Read from the dataset for the same
  // reason prerender.mjs does: a hand-copied list goes stale the moment a new
  // species is researched, and then the page exists but never gets indexed.
  ...Object.keys(legalStatus.animals).map(id => `/exotic-pet-laws/${id}/`),

  // Encyclopedia categories
  ...encyclopediaCategories.map(s => `/encyclopedia/category/${s}/`),

  // Guide category filter pages
  ...guideFilters.map(s => `/guides/category/${s}/`),

  // Fun-facts category pages
  ...factCategories.map(s => `/facts/category/${s}/`),

  // Gear pet-type filter pages
  ...gearPetTypes.map(s => `/gear/category/${s}/`),

  // Beastlypedia group filters and individual Beastfiles
  ...beastlypedia.groupSlugs.map(s => `/beastlypedia/group/${s}/`),
  ...beastlypedia.ids.map(id => `/beastlypedia/${id}/`),

  // Individual encyclopedia animal pages
  '/encyclopedia/animal/crested-gecko/',
  '/encyclopedia/animal/leopard-gecko/',
  '/encyclopedia/animal/gargoyle-gecko/',
  '/encyclopedia/animal/mourning-gecko/',
  '/encyclopedia/animal/tokay-gecko/',
  '/encyclopedia/animal/african-fat-tail/',
  '/encyclopedia/animal/leaf-tailed-gecko/',
  '/encyclopedia/animal/bearded-dragon/',
  '/encyclopedia/animal/blue-tongue-skink/',
  '/encyclopedia/animal/ackie-monitor/',
  '/encyclopedia/animal/tegu/',
  '/encyclopedia/animal/chameleon-jackson/',
  '/encyclopedia/animal/veiled-chameleon/',
  '/encyclopedia/animal/green-anole/',
  '/encyclopedia/animal/savannah-monitor/',
  '/encyclopedia/animal/uromastyx/',
  '/encyclopedia/animal/ball-python/',
  '/encyclopedia/animal/corn-snake/',
  '/encyclopedia/animal/hognose-snake/',
  '/encyclopedia/animal/boa-constrictor/',
  '/encyclopedia/animal/kingsnake/',
  '/encyclopedia/animal/milk-snake/',
  '/encyclopedia/animal/red-eared-slider/',
  '/encyclopedia/animal/russian-tortoise/',
  '/encyclopedia/animal/sulcata-tortoise/',
  '/encyclopedia/animal/box-turtle/',
  '/encyclopedia/animal/hamster/',
  '/encyclopedia/animal/hedgehog/',
  '/encyclopedia/animal/rabbit/',
  '/encyclopedia/animal/guinea-pig/',
  '/encyclopedia/animal/chinchilla/',
  '/encyclopedia/animal/ferret/',
  '/encyclopedia/animal/sugar-glider/',
  '/encyclopedia/animal/budgie/',
  '/encyclopedia/animal/cockatiel/',
  '/encyclopedia/animal/conure/',
  '/encyclopedia/animal/african-grey/',
  '/encyclopedia/animal/lovebird/',
  '/encyclopedia/animal/canary/',
  '/encyclopedia/animal/cockatoo/',
  '/encyclopedia/animal/labrador/',
  '/encyclopedia/animal/golden-retriever/',
  '/encyclopedia/animal/german-shepherd/',
  '/encyclopedia/animal/french-bulldog/',
  '/encyclopedia/animal/border-collie/',
  '/encyclopedia/animal/siberian-husky/',
  '/encyclopedia/animal/domestic-shorthair/',
  '/encyclopedia/animal/maine-coon/',
  '/encyclopedia/animal/siamese/',
  '/encyclopedia/animal/ragdoll/',
  '/encyclopedia/animal/bengal/',
  '/encyclopedia/animal/persian/',
  '/encyclopedia/animal/tarantula/',
  '/encyclopedia/animal/praying-mantis/',
  '/encyclopedia/animal/millipede/',
  '/encyclopedia/animal/hissing-cockroach/',
  '/encyclopedia/animal/stick-insect/',
  '/encyclopedia/animal/emperor-scorpion/',
  '/encyclopedia/animal/jumping-spider/',
  '/encyclopedia/animal/hermit-crab/',
  '/encyclopedia/animal/pacman-frog/',
  '/encyclopedia/animal/axolotl/',
  '/encyclopedia/animal/whites-tree-frog/',
  '/encyclopedia/animal/fire-belly-toad/',
  '/encyclopedia/animal/tiger-salamander/',
  '/encyclopedia/animal/betta-fish/',
  '/encyclopedia/animal/goldfish/',
  '/encyclopedia/animal/koi/',
  '/encyclopedia/animal/guppy/',
  '/encyclopedia/animal/angelfish/',
  '/encyclopedia/animal/corydoras-catfish/',
  '/encyclopedia/animal/neon-tetra/',
  '/encyclopedia/animal/oscar/',

  // Individual guide detail pages
  '/guides/crested-gecko/',
  '/guides/leopard-gecko/',
  '/guides/gargoyle-gecko/',
  '/guides/mourning-gecko/',
  '/guides/tokay-gecko/',
  '/guides/african-fat-tail/',
  '/guides/leaf-tailed-gecko/',
  '/guides/bearded-dragon/',
  '/guides/blue-tongue-skink/',
  '/guides/chameleon/',
  '/guides/veiled-chameleon/',
  '/guides/green-anole/',
  '/guides/ackie-monitor/',
  '/guides/savannah-monitor/',
  '/guides/uromastyx/',
  '/guides/tegu/',
  '/guides/ball-python/',
  '/guides/corn-snake/',
  '/guides/hognose-snake/',
  '/guides/boa-constrictor/',
  '/guides/california-kingsnake/',
  '/guides/milk-snake/',
  '/guides/red-eared-slider/',
  '/guides/russian-tortoise/',
  '/guides/sulcata-tortoise/',
  '/guides/box-turtle/',
  '/guides/rabbit/',
  '/guides/hamster/',
  '/guides/hedgehog/',
  '/guides/guinea-pig/',
  '/guides/chinchilla/',
  '/guides/ferret/',
  '/guides/sugar-glider/',
  '/guides/budgie/',
  '/guides/cockatiel/',
  '/guides/conure/',
  '/guides/lovebird/',
  '/guides/african-grey/',
  '/guides/canary/',
  '/guides/cockatoo/',
  '/guides/dog-universal/',
  '/guides/dog-small-breed/',
  '/guides/dog-medium-breed/',
  '/guides/dog-large-breed/',
  '/guides/dog-labrador/',
  '/guides/dog-golden-retriever/',
  '/guides/dog-german-shepherd/',
  '/guides/dog-french-bulldog/',
  '/guides/dog-border-collie/',
  '/guides/dog-siberian-husky/',
  '/guides/cat-universal/',
  '/guides/cat-domestic-shorthair/',
  '/guides/cat-maine-coon/',
  '/guides/cat-siamese/',
  '/guides/cat-ragdoll/',
  '/guides/cat-bengal/',
  '/guides/cat-persian/',
  '/guides/tarantula/',
  '/guides/praying-mantis/',
  '/guides/millipede/',
  '/guides/emperor-scorpion/',
  '/guides/hissing-cockroach/',
  '/guides/stick-insect/',
  '/guides/jumping-spider/',
  '/guides/hermit-crab/',
  '/guides/whites-tree-frog/',
  '/guides/pacman-frog/',
  '/guides/fire-belly-toad/',
  '/guides/axolotl/',
  '/guides/tiger-salamander/',
  '/guides/betta-fish/',
  '/guides/goldfish/',
  '/guides/koi/',
  '/guides/guppy/',
  '/guides/angelfish/',
  '/guides/corydoras-catfish/',
  '/guides/neon-tetra/',
  '/guides/oscar/',
];

async function generateSitemap() {
  console.log(`Building sitemap from ${mdxMeta.length} MDX post metadata entries...`);

  const chroniclesPages = getChroniclesPages();

  // Category and static pages carry no lastmod: stamping them with the build
  // date on every deploy makes the signal meaningless, and omitting lastmod
  // is valid per the sitemap spec.
  // short-stories is excluded: /blog/category/short-stories/ 301s to /chronicles/
  // /category/X/ is excluded entirely: it 301s to /blog/category/X/ (retired duplicate route)
  const blogCategoryPages = getCategorySlugs().map(slug => ({
    path: `/blog/category/${slug}/`,
    changefreq: 'weekly',
    priority: '0.7',
  }));

  const mdxPostPages = getMdxPosts();

  // Dedup static pages
  const uniqueStatic = [...new Set(staticPages)];

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

  uniqueStatic.forEach(path => {
    const isHome = path === '/';
    const isHighFreq = ['/', '/facts/', '/blog/', '/encyclopedia/', '/guides/', '/animal-facts/', '/fact-files/', '/quiz/'].includes(path);
    const isGuideCat = path.startsWith('/guides/category/');
    const isGuideDetail = path.startsWith('/guides/') && !isGuideCat;
    const isEncAnimal = path.startsWith('/encyclopedia/animal/');
    const isEncCat = path.startsWith('/encyclopedia/category/');
    const isGearCat = path.startsWith('/gear/category/');
    const changefreq = isHighFreq ? 'weekly' : (isGuideDetail || isEncAnimal) ? 'monthly' : 'weekly';
    const priority = isHome ? '1.0' : isHighFreq ? '0.9' : (isEncCat || isGuideCat || isGearCat) ? '0.7' : (isGuideDetail || isEncAnimal) ? '0.6' : '0.7';
    xml += `  <url>\n`;
    xml += `    <loc>${BASE_URL}${path}</loc>\n`;
    xml += `    <changefreq>${changefreq}</changefreq>\n`;
    xml += `    <priority>${priority}</priority>\n`;
    xml += `  </url>\n`;
  });

  [...blogCategoryPages, ...mdxPostPages, ...chroniclesPages].forEach(page => {
    xml += `  <url>\n`;
    xml += `    <loc>${BASE_URL}${page.path}</loc>\n`;
    if (page.lastmod) xml += `    <lastmod>${page.lastmod}</lastmod>\n`;
    xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    xml += `    <priority>${page.priority}</priority>\n`;
    xml += `  </url>\n`;
  });

  xml += `</urlset>`;

  fs.writeFileSync('./dist/sitemap.xml', xml);
  console.log(`Sitemap written: ${uniqueStatic.length} static + ${blogCategoryPages.length} blog categories + ${mdxPostPages.length} MDX posts + ${chroniclesPages.length} chronicles`);
}

generateSitemap().catch(err => {
  console.error('Failed to generate sitemap:', err);
  process.exit(1);
});
