import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { themedQuizzes } from './src/lib/data/quizzes/index.js';
import { CARE_PACKAGES } from './src/lib/data/carePackages.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Every post's metadata, regenerated by scripts/sync-articles.js earlier in the
// same `npm run build` chain (see package.json), so it's always in sync with
// content/. Same source prerender.mjs derives its route list from, so the
// sitemap can't list a URL that wasn't prerendered (or vice versa).
const mdxMeta = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/mdx-meta.json'), 'utf8')
);

// Generated by scripts/generate-beastlypedia-index.js, and read by prerender.mjs
// from the same file - so the sitemap cannot list a Beastfile that was never
// prerendered, which is exactly the drift the hand-mirrored lists below invite.
const beastlypedia = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/beastlypedia-index.json'), 'utf8')
);

// The legal matrix, read by prerender.mjs from this same file, for the same
// reason as the two above: a hand-copied species list goes stale the moment a
// new animal is researched, and then the page exists but is never indexed.
const legalStatus = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/data/legalStatus.json'), 'utf8')
);

// Individual encyclopedia animal and guide detail pages, generated by
// scripts/generate-encyclopedia-index.js and scripts/generate-guides-index.js
// (same build-chain order as above), read here for the same reason: a
// hand-copied id list goes stale the moment a new species is added. That's
// exactly what used to happen, 18 species added in one session never made it
// into this sitemap because their ids were never added to a hardcoded array.
const encyclopediaIndex = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/encyclopedia-index.json'), 'utf8')
);
const guidesIndex = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'src/lib/generated/guides-index.json'), 'utf8')
);

function parseFrontmatter(content) {
  // \r? - MDX files in this repo are a mix of LF and CRLF line endings;
  // an LF-only match silently drops frontmatter and the slug falls back
  // to the filename, putting wrong URLs in the sitemap.
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const result = {};
  for (const line of match[1].split(/\r?\n/)) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    const val = line.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, '');
    result[key] = val;
  }
  return result;
}

// Mirrors slugify in src/lib/utils/slugify.js (incl. the "&"/"and" rule that
// makes "Small & Exotic Pets" produce "small-and-exotic-pets").
const slugifyCategory = (text) => text.toString().toLowerCase()
  .replace(/\s*&\s*|\s+and\s+/g, '-and-')
  .replace(/\s+/g, '-')
  .replace(/[^a-z0-9-]/g, '')
  .replace(/-+/g, '-')
  .replace(/^-|-$/g, '');

// Blog category slugs, one per category that actually has at least one post -
// Blog.jsx renders a pill for each of those and prerender.mjs prerenders them
// (see getMdxCategoryRoutes there), so they belong in the sitemap too.
// Excludes the two retired ones that 301 away (site-news, short-stories).
function getCategorySlugs() {
  const slugs = new Set();
  for (const post of mdxMeta) {
    // All categories the post is filed under, not just the primary one.
    const cats = (post.categories?.length ? post.categories : [post.category]).filter(Boolean);
    for (const cat of cats) {
      const slug = slugifyCategory(cat);
      if (!slug || slug === 'site-news' || slug === 'short-stories') continue;
      slugs.add(slug);
    }
  }
  return [...slugs];
}

// Chronicles series slug prefixes (mirrors CHRONICLES_SERIES in src/lib/chronicles.js).
// Their stories live at /chronicles/<id>/<part>/, not /blog/<slug>/.
const chroniclesPrefixes = { dex: 'chronicles-of-dex', otis: 'chronicles-of-otis' };
const isChroniclesSlug = (slug) =>
  Object.values(chroniclesPrefixes).some(prefix => slug.startsWith(prefix));

// mdx-meta.json carries the publish date but not `lastUpdated`, and lastmod
// should reflect the newer of the two when a post has been revised, so read it
// back out of the source file's frontmatter (post.path is repo-relative, e.g.
// "/content/guides/koi-cost-guide.mdx").
function readLastUpdated(post) {
  const filePath = path.join(__dirname, post.path);
  if (!fs.existsSync(filePath)) return null;
  return parseFrontmatter(fs.readFileSync(filePath, 'utf8')).lastUpdated || null;
}

// Google discovers images fastest through the sitemap's image extension,
// rather than waiting to crawl and render each page. Two sources per post:
// the frontmatter featured image (image/imageAlt, already known from
// mdxMeta) and any <Figure src="..." alt="..." /> embedded in the body
// (attribute order not guaranteed, so src/alt are matched independently).
function getFigureImages(post) {
  const filePath = path.join(__dirname, post.path);
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const figureTags = content.match(/<Figure\s[^>]*\/>/g) || [];
  return figureTags
    .map(tag => {
      const srcMatch = tag.match(/src=["']([^"']+)["']/);
      const altMatch = tag.match(/alt=["']([^"']+)["']/);
      return srcMatch ? { loc: srcMatch[1], title: altMatch ? altMatch[1] : '' } : null;
    })
    .filter(Boolean);
}

function getPostImages(post) {
  const images = [];
  if (post.image) images.push({ loc: post.image, title: post.imageAlt || post.title });
  images.push(...getFigureImages(post));
  return images;
}

// Escapes the five XML-reserved characters in a title/alt string pulled from
// content, since & and < in particular would otherwise produce invalid XML.
function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// A post's date can be set ahead as a release date (see hasReachedPublishDate in
// public/_worker.js). The page itself stays in the sitemap either way, since it is
// deployed and we want it crawled, but a <lastmod> in the future is a bad signal:
// it claims the page changed on a day that has not happened. Drop it until then.
const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
const notInFuture = (date) => (date && String(date).slice(0, 10) <= today ? date : null);

function getMdxPosts() {
  // Short stories live on /chronicles/, not /blog/ (old URLs 301 in _redirects)
  return mdxMeta.filter(post => !isChroniclesSlug(post.slug)).map(post => ({
    path: `/blog/${post.slug}/`,
    // Only emit lastmod when the frontmatter carries a real, already-reached date - a
    // fabricated build-date lastmod is worse than none at all, and so is a future one.
    lastmod: notInFuture(readLastUpdated(post)) || notInFuture(post.date) || null,
    changefreq: 'weekly',
    priority: '0.7',
    images: getPostImages(post),
  }));
}

// /chronicles/<series>/ (landing list) + /chronicles/<series>/<n>/ per part.
// Part counts = the MDX short-story posts per series.
function getChroniclesPages() {
  const dedupedSlugs = [...new Set(mdxMeta.map(post => post.slug).filter(isChroniclesSlug))];

  const pages = [];
  for (const [id, prefix] of Object.entries(chroniclesPrefixes)) {
    const partCount = dedupedSlugs.filter(s => s.startsWith(prefix)).length;
    pages.push({ path: `/chronicles/${id}/`, changefreq: 'weekly', priority: '0.7' });
    for (let n = 1; n <= partCount; n++) {
      pages.push({ path: `/chronicles/${id}/${n}/`, changefreq: 'weekly', priority: '0.7' });
    }
  }
  return pages;
}

const BASE_URL = 'https://beastlyfacts.com';

// Encyclopedia category slugs (mirrors encyclopediaCategories in encyclopedia.js)
const encyclopediaCategories = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Guide filter slugs (mirrors guideFilters in Encyclopedia.jsx, excluding 'all')
const guideFilters = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Fun-facts category slugs (mirrors `categories` in src/lib/data/facts.js, slugified)
const factCategories = [
  'birds', 'dogs-and-cats', 'fish', 'invertebrates', 'mammals', 'ocean', 'reptiles', 'weird-and-wonderful',
];

// Not listed here, on purpose: /gear/ and its five pet-type filters,
// /gallery/, /categories/, and the three /care-packages/ subpages (store,
// why-we-exist, faq). Each carries noindex,follow in its page component. Over
// three months of Search Console data they earned one click between them, and
// listing a noindexed URL in a sitemap is a contradiction Google reports as an
// error. They stay prerendered and linked for readers; they are just not
// submitted for indexing.

const staticPages = [
  '/',
  '/about/',
  '/contact/',
  '/facts/',
  '/animal-facts/',
  '/fact-files/',
  // /feed/ deliberately omitted: its posts are fetched from Supabase at
  // runtime and the route is not prerendered, so a crawler that does not run
  // JS gets an empty shell - Google logged it as a soft 404. It is noindex in
  // Feed.jsx to match, so submitting it here would only contradict that.
  '/blog/',
  '/encyclopedia/',
  '/beastlypedia/',
  '/guides/',
  '/quiz/',
  '/quiz/personality/',
  '/quiz/trivia/',
  '/quiz/knowledge/',
  ...themedQuizzes.map(q => `/quiz/${q.id}/`),
  '/glossary/',
  '/exotic-pet-laws/',
  '/care-packages/',

  // Product pages for packages sold on this site. Same list prerender.mjs
  // builds its routes from, so the sitemap cannot offer a URL that was never
  // rendered. Gumroad packages are not here: their product page is Gumroad's.
  // /care-packages/thanks/ and /care-packages/library/ are not here either -
  // both are noindex,nofollow, and listing a noindexed URL in a sitemap is the
  // contradiction the note above is about.
  ...CARE_PACKAGES.filter(p => p.storefront === 'stripe' || p.storefront === 'soon').map(p => `/care-packages/${p.id}/`),

  // One page per animal in the legal matrix. Read from the dataset for the same
  // reason prerender.mjs does: a hand-copied list goes stale the moment a new
  // species is researched, and then the page exists but never gets indexed.
  //
  // Animals with no restriction in any jurisdiction are left out. Their page is
  // an all-grey map and a single sentence, so it carries noindex, and listing a
  // noindexed URL in the sitemap is a contradiction. Derived from the same data
  // the page uses, so the two cannot drift apart.
  ...Object.entries(legalStatus.animals)
    .filter(([, a]) => Object.values(a.jurisdictions).some(e => e.status !== 'legal'))
    .map(([id]) => `/exotic-pet-laws/${id}/`),

  // Encyclopedia categories
  ...encyclopediaCategories.map(s => `/encyclopedia/category/${s}/`),

  // Guide category filter pages
  ...guideFilters.map(s => `/guides/category/${s}/`),

  // Fun-facts category pages
  ...factCategories.map(s => `/facts/category/${s}/`),

  // Beastlypedia group filters and individual Beastfiles
  ...beastlypedia.groupSlugs.map(s => `/beastlypedia/group/${s}/`),
  ...beastlypedia.ids.map(id => `/beastlypedia/${id}/`),

  // Individual encyclopedia animal pages
  ...encyclopediaIndex.animals.map(a => `/encyclopedia/animal/${a.id}/`),

  // Individual guide detail pages
  ...guidesIndex.guides.map(g => `/guides/${g.id}/`),
];

async function generateSitemap() {
  console.log(`Building sitemap from ${mdxMeta.length} MDX post metadata entries...`);

  const chroniclesPages = getChroniclesPages();

  // Category and static pages carry no lastmod: stamping them with the build
  // date on every deploy makes the signal meaningless, and omitting lastmod
  // is valid per the sitemap spec.
  // short-stories is excluded: /blog/category/short-stories/ 301s to /chronicles/
  // /category/X/ is excluded entirely: it 301s to /blog/category/X/ (retired duplicate route)
  const blogCategoryPages = getCategorySlugs().map(slug => ({
    path: `/blog/category/${slug}/`,
    changefreq: 'weekly',
    priority: '0.7',
  }));

  const mdxPostPages = getMdxPosts();

  // Dedup static pages
  const uniqueStatic = [...new Set(staticPages)];

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n`;

  uniqueStatic.forEach(path => {
    const isHome = path === '/';
    const isHighFreq = ['/', '/facts/', '/blog/', '/encyclopedia/', '/guides/', '/animal-facts/', '/fact-files/', '/quiz/'].includes(path);
    const isGuideCat = path.startsWith('/guides/category/');
    const isGuideDetail = path.startsWith('/guides/') && !isGuideCat;
    const isEncAnimal = path.startsWith('/encyclopedia/animal/');
    const isEncCat = path.startsWith('/encyclopedia/category/');
    const changefreq = isHighFreq ? 'weekly' : (isGuideDetail || isEncAnimal) ? 'monthly' : 'weekly';
    const priority = isHome ? '1.0' : isHighFreq ? '0.9' : (isEncCat || isGuideCat) ? '0.7' : (isGuideDetail || isEncAnimal) ? '0.6' : '0.7';
    xml += `  <url>\n`;
    xml += `    <loc>${BASE_URL}${path}</loc>\n`;
    xml += `    <changefreq>${changefreq}</changefreq>\n`;
    xml += `    <priority>${priority}</priority>\n`;
    xml += `  </url>\n`;
  });

  [...blogCategoryPages, ...mdxPostPages, ...chroniclesPages].forEach(page => {
    xml += `  <url>\n`;
    xml += `    <loc>${BASE_URL}${page.path}</loc>\n`;
    if (page.lastmod) xml += `    <lastmod>${page.lastmod}</lastmod>\n`;
    xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    xml += `    <priority>${page.priority}</priority>\n`;
    (page.images || []).forEach(img => {
      xml += `    <image:image>\n`;
      xml += `      <image:loc>${BASE_URL}${img.loc}</image:loc>\n`;
      if (img.title) xml += `      <image:title>${escapeXml(img.title)}</image:title>\n`;
      xml += `    </image:image>\n`;
    });
    xml += `  </url>\n`;
  });

  xml += `</urlset>`;

  fs.writeFileSync('./dist/sitemap.xml', xml);
  console.log(`Sitemap written: ${uniqueStatic.length} static + ${blogCategoryPages.length} blog categories + ${mdxPostPages.length} MDX posts + ${chroniclesPages.length} chronicles`);
}

generateSitemap().catch(err => {
  console.error('Failed to generate sitemap:', err);
  process.exit(1);
});
