/**
 * prerender.mjs
 *
 * Runs after `vite build`. Starts a local Vite preview server, visits every
 * route with a headless browser, and writes the fully-rendered HTML to
 * dist/<route>/index.html so Netlify serves real content to crawlers without
 * needing JavaScript.
 *
 * Dynamic /blog/:slug and /blog/category/:slug routes are derived from the MDX
 * post metadata at build time.
 */

import puppeteer from 'puppeteer';
import { preview } from 'vite';
import { mkdir, writeFile, readFile } from 'fs/promises';
import path from 'path';

const DIST = './dist';
const PORT = 4173;
const BASE_URL = `http://localhost:${PORT}`;

// Every post's metadata, regenerated by scripts/sync-articles.js earlier in the
// same `npm run build` chain (see package.json), so it's always in sync with
// content/ by the time this runs. It's also what src/lib/mdxPosts.js builds the
// live site's post list from, so routes derived here can't drift from the pages
// the app will actually render.
const MDX_META_PATH = 'src/lib/generated/mdx-meta.json';

// Encyclopedia category slugs (mirrors encyclopediaCategories in encyclopedia.js)
const ENCYCLOPEDIA_CATEGORIES = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Fun-facts category slugs (mirrors `categories` in src/lib/data/facts.js, slugified)
const FACT_CATEGORIES = [
  'birds', 'dogs-and-cats', 'mammals', 'ocean', 'reptiles', 'weird-and-wonderful',
];

// Gear pet-type filter slugs (mirrors GEAR_PET_TYPES in src/lib/data/affiliateProducts.js)
const GEAR_PET_TYPES = [
  'reptiles-amphibians', 'birds', 'fish', 'dogs-cats', 'small-mammals',
];

// Chronicles series slug prefixes (mirrors CHRONICLES_SERIES in src/lib/chronicles.js).
// Their stories render on /chronicles/<id>/<part>, not /blog/<slug> - the old
// blog URLs 301 in public/_redirects.
const CHRONICLES_PREFIXES = { dex: 'chronicles-of-dex', otis: 'chronicles-of-otis' };
const isChroniclesSlug = (slug) =>
  Object.values(CHRONICLES_PREFIXES).some(prefix => slug.startsWith(prefix));

// Mirrors slugify in src/lib/utils/slugify.js (incl. the "&"/"and" rule that
// makes "Small & Exotic Pets" produce "small-and-exotic-pets").
const slugifyCategory = (text) => text.toString().toLowerCase()
  .replace(/\s*&\s*|\s+and\s+/g, '-and-')
  .replace(/\s+/g, '-')
  .replace(/[^a-z0-9-]/g, '')
  .replace(/-+/g, '-')
  .replace(/^-|-$/g, '');

// Blog post routes, one per MDX post. Chronicles posts are excluded by slug
// prefix (not by category tag) so this can't silently break if the "Short
// Stories" category gets renamed/re-slugged - they render on /chronicles/
// instead, and their old /blog/ URLs 301 in public/_redirects.
function getMdxRoutes(meta) {
  return meta
    .filter(post => !isChroniclesSlug(post.slug))
    .map(post => `/blog/${post.slug}`);
}

// Blog category pages, one per category that actually has at least one post -
// Blog.jsx renders a pill for each of those, so they need prerendered pages or
// the pill links 404 on a hard load.
// /category/X 301s to /blog/category/X in _redirects (retired duplicate route) - don't prerender it.
function getMdxCategoryRoutes(meta) {
  const routes = new Set();
  for (const post of meta) {
    // Every category the post is filed under, not just the primary one, so a
    // post tagged both Aquatic Life and Wild Animals prerenders under each.
    const cats = (post.categories?.length ? post.categories : [post.category]).filter(Boolean);
    for (const cat of cats) {
      const slug = slugifyCategory(cat);
      // site-news 301s to the welcome post; short-stories 301s to /chronicles/
      if (!slug || slug === 'site-news' || slug === 'short-stories') continue;
      routes.add(`/blog/category/${slug}`);
    }
  }
  return [...routes];
}

// Chronicles part routes: /chronicles/<series> (part 1) plus /chronicles/<series>/<n>.
// Parts = the MDX short-story posts per series - must stay consistent with
// groupChronicles() in src/lib/chronicles.js.
function getChroniclesRoutes(meta) {
  const slugs = [...new Set(meta.map(post => post.slug).filter(isChroniclesSlug))];

  const routes = [];
  for (const [id, prefix] of Object.entries(CHRONICLES_PREFIXES)) {
    const partCount = slugs.filter(s => s.startsWith(prefix)).length;
    routes.push(`/chronicles/${id}`); // landing list
    for (let n = 1; n <= partCount; n++) routes.push(`/chronicles/${id}/${n}`);
  }
  return routes;
}

// All encyclopedia animal IDs (mirrors encyclopediaAnimals in encyclopedia.js)
const ENCYCLOPEDIA_ANIMAL_IDS = [
  'crested-gecko','leopard-gecko','gargoyle-gecko','mourning-gecko','tokay-gecko',
  'african-fat-tail','leaf-tailed-gecko',
  'bearded-dragon','blue-tongue-skink','ackie-monitor','tegu','chameleon-jackson','veiled-chameleon',
  'green-anole','savannah-monitor','uromastyx',
  'ball-python','corn-snake','hognose-snake','boa-constrictor','kingsnake','milk-snake',
  'red-eared-slider','russian-tortoise','sulcata-tortoise','box-turtle',
  'hamster','hedgehog','rabbit','guinea-pig','chinchilla','ferret','sugar-glider',
  'budgie','cockatiel','conure','african-grey','lovebird','canary','cockatoo',
  'labrador','golden-retriever','german-shepherd','french-bulldog','border-collie','siberian-husky',
  'domestic-shorthair','maine-coon','siamese','ragdoll','bengal','persian',
  'tarantula','praying-mantis','millipede','hissing-cockroach','stick-insect','emperor-scorpion',
  'jumping-spider','hermit-crab',
  'pacman-frog','axolotl','whites-tree-frog','fire-belly-toad','tiger-salamander',
  'betta-fish','goldfish','koi','guppy','angelfish','corydoras-catfish','neon-tetra','oscar',
];

// All care guide IDs (mirrors guidesExtended.js + dogCatGuides.js)
const GUIDE_IDS = [
  'crested-gecko','leopard-gecko','gargoyle-gecko','mourning-gecko','hognose-snake',
  'chameleon','veiled-chameleon','ball-python','bearded-dragon','blue-tongue-skink','corn-snake',
  'ackie-monitor','boa-constrictor','tegu','leaf-tailed-gecko','red-eared-slider',
  'hamster','rabbit','hedgehog','guinea-pig','chinchilla','sugar-glider','african-grey',
  'budgie','lovebird','tokay-gecko','african-fat-tail','uromastyx','savannah-monitor',
  'green-anole','california-kingsnake','milk-snake','russian-tortoise','sulcata-tortoise',
  'box-turtle','ferret','tarantula','praying-mantis','millipede','emperor-scorpion',
  'hissing-cockroach','stick-insect','jumping-spider','hermit-crab','whites-tree-frog','pacman-frog','fire-belly-toad',
  'axolotl','tiger-salamander','cockatiel','conure','canary','cockatoo',
  'dog-universal','dog-small-breed','dog-medium-breed','dog-large-breed','dog-labrador',
  'dog-golden-retriever','dog-german-shepherd','dog-french-bulldog','dog-border-collie',
  'dog-siberian-husky','cat-universal','cat-domestic-shorthair','cat-maine-coon',
  'cat-siamese','cat-ragdoll','cat-bengal','cat-persian',
  'betta-fish','goldfish','koi','guppy','angelfish','corydoras-catfish','neon-tetra','oscar',
];

// Static routes - must match App.jsx routes. Excludes only the couple of
// routes with no stable default to render (e.g. /donate/success, /donate/cancel
// depend on Stripe redirect query params) - see the "no SPA-fallback" comment
// in public/_redirects for what happens to those at request time. /pack is
// noindex,follow but IS included: without a prerendered file, Cloudflare falls
// through to a 404 for it, and a stale cached copy of that fallback (from
// before this file's SPA-fallback rules were tightened up) kept getting served
// with 200 status and long-dead JS/CSS hashes - see the Ahrefs "broken JS/CSS"
// errors this fixed. Prerendering it gives it the same reliable per-deploy
// static file every other route gets, sidestepping that whole failure mode.
const STATIC_ROUTES = [
  '/',
  '/facts',
  '/blog',
  '/encyclopedia',
  '/guides',
  '/gear',
  '/pack',
  '/quiz/personality',
  '/quiz/trivia',
  '/quiz/knowledge',
  '/about',
  '/contact',
  '/glossary',
  '/animal-facts',
  '/fact-files',
  '/gallery',
  '/categories',
  '/search',
  '/donate',
  '/terms',
  '/privacy',
  ...ENCYCLOPEDIA_CATEGORIES.map(s => `/encyclopedia/category/${s}`),
  ...ENCYCLOPEDIA_CATEGORIES.map(s => `/guides/category/${s}`),
  ...FACT_CATEGORIES.map(s => `/facts/category/${s}`),
  ...GEAR_PET_TYPES.map(s => `/gear/category/${s}`),
  ...ENCYCLOPEDIA_ANIMAL_IDS.map(id => `/encyclopedia/animal/${id}`),
  ...GUIDE_IDS.map(id => `/guides/${id}`),
];

// 45s, not 30s: the Cloudflare Pages build runner is shared/contended, and
// with 600 routes across 4 concurrent tabs even a routine CPU-scheduling
// hiccup can push a page past a tight deadline (many routes already need
// 2-4 attempts to pass under the old 30s timeout - see MAX_ATTEMPTS below).
const NAV_TIMEOUT_MS = 45000;

async function renderRoute(page, route) {
  const url = `${BASE_URL}${route}`;
  await page.goto(url, { waitUntil: 'networkidle0', timeout: NAV_TIMEOUT_MS });

  // networkidle0 fires when the JS chunk downloads, but react-helmet-async
  // may not have applied this route's <head> yet. Don't capture until the
  // canonical equals this route's production URL and a meta description is
  // present (noindex pages are exempt - they opt out of SEO tags). Every
  // route including '/' must pass. A timeout is a hard failure: capturing
  // early ships a generic <head> to production, which is worse than a
  // failed build. Timeouts are retried by renderWorker.
  const expectedCanonical = `https://beastlyfacts.com${route === '/' ? '/' : `${route}/`}`;
  await page.waitForFunction(
    (expected) => {
      const robots = document.querySelector('meta[name="robots"]');
      if (robots && /noindex/i.test(robots.getAttribute('content') || '')) return true;
      // MDX article bodies are lazy-loaded (see mdxPosts.js); the Suspense
      // fallback carries [data-mdx-loading] - don't capture until it's gone,
      // or the prerendered HTML ships without the article text.
      if (document.querySelector('[data-mdx-loading]')) return false;
      const canonical = document.querySelector('link[rel="canonical"]');
      const description = document.querySelector('meta[name="description"]');
      return Boolean(
        canonical && canonical.getAttribute('href') === expected &&
        description && description.getAttribute('content')
      );
    },
    { timeout: NAV_TIMEOUT_MS },
    expectedCanonical
  );

  // Normalize every inline style attribute to React's own serialization
  // format before capturing HTML. The browser's native cssText format is
  // "key: value; key2: value2;" (space after the colon, trailing
  // semicolon) - but React computes its OWN hydration-comparison string
  // from the style object prop as "key:value;key2:value2" (no spaces, no
  // trailing semicolon). Same value, different text, and React's hydration
  // check is a literal string comparison - confirmed directly (multiple
  // times, on both framer-motion-managed and completely plain <div
  // style={...}> elements) that this mismatches on every single build
  // regardless of the actual value, since normal SSR via react-dom/server
  // doesn't hit this (both sides use React's own serializer) but this app's
  // "server" HTML comes from a real browser's live DOM instead. Rewriting
  // every element's style attribute here, from the parsed CSSStyleDeclaration
  // (not string-splitting cssText, which would break on values containing
  // ";" like url() data URIs), makes the captured HTML byte-for-byte match
  // what a real client's hydration-critical render expects.
  await page.evaluate(() => {
    document.querySelectorAll('[style]').forEach((el) => {
      const style = el.style;
      const parts = [];
      for (let i = 0; i < style.length; i++) {
        const prop = style[i];
        const value = style.getPropertyValue(prop);
        const priority = style.getPropertyPriority(prop);
        parts.push(`${prop}:${value}${priority ? ' !important' : ''}`);
      }
      el.setAttribute('style', parts.join(';'));
    });
  });

  return page.content();
}

// A path guaranteed not to match any real route, so it always renders the
// wildcard PageNotFound component - reusing the real app's styling/links
// instead of hand-maintaining a separate static 404 page.
const NOT_FOUND_PROBE_ROUTE = '/__prerender_404_probe__';

async function saveHtml(route, html) {
  const filePath =
    route === '/'
      ? path.join(DIST, 'index.html')
      : path.join(DIST, route.replace(/^\//, ''), 'index.html');

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, html, 'utf-8');
}

// 4 tabs, not 8: each tab parses the full JS bundle, and heavy pages
// (/facts, /encyclopedia, /blog) get CPU-starved at higher concurrency - their <head> never applies within the wait window and the build fails.
const CONCURRENCY = 4;
const MAX_ATTEMPTS = 5; // retries per route before giving up on it
// Delay before each retry (scaled by attempt number) - gives a transient CPU
// spike on the shared build runner time to clear instead of immediately
// re-contending with the same 3 other buckets that are also mid-render.
const RETRY_BACKOFF_MS = 1500;

async function renderWorker(browser, routes, results) {
  for (const route of routes) {
    let lastErr = null;
    let done = false;
    for (let attempt = 1; attempt <= MAX_ATTEMPTS && !done; attempt++) {
      if (attempt > 1) await new Promise(r => setTimeout(r, RETRY_BACKOFF_MS * attempt));
      const page = await browser.newPage();
      // All 600+ routes render through ONE browser instance sharing the same
      // origin, so localStorage persists across every page.newPage() call in
      // this loop unless explicitly cleared. That didn't matter before, but
      // now that main.jsx defers reading localStorage-backed state (dark
      // mode, visit streak, favorites - see useLocalStorage.js) to an effect
      // instead of a hydration-mismatching lazy useState initializer, that
      // same effect also runs during prerendering (a real browser, not SSR)
      // and writes real values (e.g. recordVisit() incrementing the streak)
      // that would otherwise leak into every subsequently-rendered page,
      // making prerendered output non-deterministic and no longer matching
      // the fresh-visitor baseline hydration needs to reproduce.
      await page.evaluateOnNewDocument(() => {
        try { localStorage.clear(); sessionStorage.clear(); } catch {}
        // Read effects (dark mode/favorites/streak - see useLocalStorage.js)
        // are harmless to run against the now-guaranteed-empty localStorage
        // above, but recordVisit() (FavoritesContext.jsx) unconditionally
        // WRITES a new streak value even on a "no prior visit" start, and
        // its exact timing relative to prerender.mjs's own wait condition
        // (Helmet's meta tags settling) is an unrelated race - capturing
        // mid-write would bake a value into the static HTML that doesn't
        // match the real client's guaranteed-default first render either
        // way. Skipping it during prerendering keeps captured HTML at the
        // same default state hydration will always start from.
        window.__IS_PRERENDER__ = true;
      });
      await page.setRequestInterception(true);
      page.on('request', req => {
        const u = req.url();
        if (u.includes('googletagmanager') || u.includes('google-analytics') ||
            u.includes('pagead') || u.includes('fundingchoices') ||
            u.includes('fonts.googleapis.com') || u.includes('fonts.gstatic.com')) {
          req.abort();
        } else {
          req.continue();
        }
      });
      try {
        const html = await renderRoute(page, route);
        await saveHtml(route, html);
        console.log(`  ✓ ${route}${attempt > 1 ? ` (attempt ${attempt})` : ''}`);
        results.passed++;
        done = true;
      } catch (err) {
        lastErr = err;
      } finally {
        await page.close();
      }
    }
    if (!done) {
      console.warn(`  ✗ ${route} - ${lastErr.message}`);
      results.failed++;
    }
  }
}

async function main() {
  // On Cloudflare Pages, skip prerender for non-production branches (preview deploys).
  // Set CF_PAGES_BRANCH in the Cloudflare Pages env vars, or SKIP_PRERENDER=true to always skip.
  const branch = process.env.CF_PAGES_BRANCH;
  if (process.env.SKIP_PRERENDER === 'true' || (branch && branch !== 'main')) {
    console.log(`Skipping prerender (branch: ${branch || 'unknown'}, SKIP_PRERENDER=${process.env.SKIP_PRERENDER})`);
    process.exit(0);
  }

  console.log('🔍 Discovering dynamic routes from MDX metadata...');
  const mdxMeta = JSON.parse(await readFile(MDX_META_PATH, 'utf-8'));
  const mdxCategoryRoutes = getMdxCategoryRoutes(mdxMeta);
  const mdxRoutes = getMdxRoutes(mdxMeta);
  const chroniclesRoutes = getChroniclesRoutes(mdxMeta);
  const allRoutes = [...new Set([...STATIC_ROUTES, ...mdxCategoryRoutes, ...mdxRoutes, ...chroniclesRoutes])];
  console.log(`📄 Prerendering ${allRoutes.length} routes with concurrency ${CONCURRENCY}...`);

  const server = await preview({ preview: { port: PORT, open: false } });
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });

  // Split routes into CONCURRENCY buckets and run in parallel
  const results = { passed: 0, failed: 0 };
  const buckets = Array.from({ length: CONCURRENCY }, (_, i) =>
    allRoutes.filter((_, j) => j % CONCURRENCY === i)
  );
  await Promise.all(buckets.map(bucket => renderWorker(browser, bucket, results)));

  // Cloudflare Pages serves a literal 404.html (with a real 404 status) for
  // any request that doesn't match a static asset or an explicit _redirects
  // rule. Generate it from the actual app instead of hand-writing a separate
  // page, so it always matches the live PageNotFound component/styling.
  try {
    const page = await browser.newPage();
    await page.evaluateOnNewDocument(() => {
      try { localStorage.clear(); sessionStorage.clear(); } catch {}
      window.__IS_PRERENDER__ = true;
    });
    const html = await renderRoute(page, NOT_FOUND_PROBE_ROUTE);
    await writeFile(path.join(DIST, '404.html'), html, 'utf-8');
    await page.close();
    console.log('  ✓ 404.html');
  } catch (err) {
    console.warn(`  ✗ 404.html - ${err.message}`);
    results.failed++;
  }

  await browser.close();
  server.httpServer.close();

  console.log(`\n🎉 Prerender complete: ${results.passed} succeeded, ${results.failed} failed.`);

  // A route that fails prerendering doesn't 404 - it just falls back to the
  // plain client-rendered SPA shell (see the "no SPA-fallback" comment on
  // STATIC_ROUTES for the routes that don't even get that). That's a worse
  // outcome for that one page's SEO, but failing the entire build over 1-2
  // flaky routes blocks every OTHER page's update too, on a shared/contended
  // build runner where isolated timeouts are expected occasionally even
  // after 5 retries. Only hard-fail when failures are widespread enough to
  // suggest a real, systemic problem worth blocking the deploy over.
  const FAILURE_THRESHOLD = 3;
  if (results.failed > FAILURE_THRESHOLD) {
    console.error(`❌ ${results.failed} routes failed prerendering (threshold: ${FAILURE_THRESHOLD}) - failing build.`);
    process.exit(1);
  }
  if (results.failed > 0) {
    console.warn(`⚠️  ${results.failed} route(s) failed prerendering but under the threshold - deploying anyway. Affected routes will serve client-rendered until fixed.`);
  }
}

main().catch(err => {
  console.error('❌ Prerender script crashed:', err);
  process.exit(1);
});
