/**
 * prerender.mjs
 *
 * Runs after `vite build`. Starts a local Vite preview server, visits every
 * route with a headless browser, and writes the fully-rendered HTML to
 * dist/<route>/index.html so Netlify serves real content to crawlers without
 * needing JavaScript.
 *
 * Dynamic /blog/:slug and /blog/category/:slug routes are derived from the MDX
 * post metadata at build time.
 */

import puppeteer from 'puppeteer';
import { preview } from 'vite';
import { mkdir, writeFile, readFile } from 'fs/promises';
import { readFileSync } from 'fs';
import path from 'path';
import { cpus } from 'os';

const DIST = './dist';
const PORT = 4173;
const BASE_URL = `http://localhost:${PORT}`;

// Every post's metadata, regenerated by scripts/sync-articles.js earlier in the
// same `npm run build` chain (see package.json), so it's always in sync with
// content/ by the time this runs. It's also what src/lib/mdxPosts.js builds the
// live site's post list from, so routes derived here can't drift from the pages
// the app will actually render.
const MDX_META_PATH = 'src/lib/generated/mdx-meta.json';

// Encyclopedia category slugs (mirrors encyclopediaCategories in encyclopedia.js)
const ENCYCLOPEDIA_CATEGORIES = [
  'geckos', 'lizards', 'snakes', 'turtles-tortoises',
  'small-mammals', 'birds', 'dogs', 'cats', 'invertebrates', 'amphibians', 'fish',
];

// Fun-facts category slugs (mirrors `categories` in src/lib/data/facts.js, slugified)
const FACT_CATEGORIES = [
  'birds', 'dogs-and-cats', 'mammals', 'ocean', 'reptiles', 'weird-and-wonderful',
];

// Gear pet-type filter slugs (mirrors GEAR_PET_TYPES in src/lib/data/affiliateProducts.js)
const GEAR_PET_TYPES = [
  'reptiles-amphibians', 'birds', 'fish', 'dogs-cats', 'small-mammals',
];

// Chronicles series slug prefixes (mirrors CHRONICLES_SERIES in src/lib/chronicles.js).
// Their stories render on /chronicles/<id>/<part>, not /blog/<slug> - the old
// blog URLs 301 in public/_redirects.
const CHRONICLES_PREFIXES = { dex: 'chronicles-of-dex', otis: 'chronicles-of-otis' };
const isChroniclesSlug = (slug) =>
  Object.values(CHRONICLES_PREFIXES).some(prefix => slug.startsWith(prefix));

// Mirrors slugify in src/lib/utils/slugify.js (incl. the "&"/"and" rule that
// makes "Small & Exotic Pets" produce "small-and-exotic-pets").
const slugifyCategory = (text) => text.toString().toLowerCase()
  .replace(/\s*&\s*|\s+and\s+/g, '-and-')
  .replace(/\s+/g, '-')
  .replace(/[^a-z0-9-]/g, '')
  .replace(/-+/g, '-')
  .replace(/^-|-$/g, '');

// Blog post routes, one per MDX post. Chronicles posts are excluded by slug
// prefix (not by category tag) so this can't silently break if the "Short
// Stories" category gets renamed/re-slugged - they render on /chronicles/
// instead, and their old /blog/ URLs 301 in public/_redirects.
function getMdxRoutes(meta) {
  return meta
    .filter(post => !isChroniclesSlug(post.slug))
    .map(post => `/blog/${post.slug}`);
}

// Blog category pages, one per category that actually has at least one post -
// Blog.jsx renders a pill for each of those, so they need prerendered pages or
// the pill links 404 on a hard load.
// /category/X 301s to /blog/category/X in _redirects (retired duplicate route) - don't prerender it.
function getMdxCategoryRoutes(meta) {
  const routes = new Set();
  for (const post of meta) {
    // Every category the post is filed under, not just the primary one, so a
    // post tagged both Aquatic Life and Wild Animals prerenders under each.
    const cats = (post.categories?.length ? post.categories : [post.category]).filter(Boolean);
    for (const cat of cats) {
      const slug = slugifyCategory(cat);
      // site-news 301s to the welcome post; short-stories 301s to /chronicles/
      if (!slug || slug === 'site-news' || slug === 'short-stories') continue;
      routes.add(`/blog/category/${slug}`);
    }
  }
  return [...routes];
}

// Chronicles part routes: /chronicles/<series> (part 1) plus /chronicles/<series>/<n>.
// Parts = the MDX short-story posts per series - must stay consistent with
// groupChronicles() in src/lib/chronicles.js.
function getChroniclesRoutes(meta) {
  const slugs = [...new Set(meta.map(post => post.slug).filter(isChroniclesSlug))];

  const routes = [];
  for (const [id, prefix] of Object.entries(CHRONICLES_PREFIXES)) {
    const partCount = slugs.filter(s => s.startsWith(prefix)).length;
    routes.push(`/chronicles/${id}`); // landing list
    for (let n = 1; n <= partCount; n++) routes.push(`/chronicles/${id}/${n}`);
  }
  return routes;
}

// Read straight from the dataset rather than hand-copying a list. This one
// grows every time a species is researched, and a stale copy here would mean a
// page that exists, renders and is linked but never gets prerendered.
const LEGAL_ANIMAL_IDS = Object.keys(
  JSON.parse(readFileSync(new URL('./src/lib/data/legalStatus.json', import.meta.url), 'utf8')).animals,
);

// All encyclopedia animal IDs (mirrors encyclopediaAnimals in encyclopedia.js)
const ENCYCLOPEDIA_ANIMAL_IDS = [
  'crested-gecko','leopard-gecko','gargoyle-gecko','mourning-gecko','tokay-gecko',
  'african-fat-tail','leaf-tailed-gecko',
  'bearded-dragon','blue-tongue-skink','ackie-monitor','tegu','chameleon-jackson','veiled-chameleon',
  'green-anole','savannah-monitor','uromastyx',
  'ball-python','corn-snake','hognose-snake','boa-constrictor','kingsnake','milk-snake',
  'red-eared-slider','russian-tortoise','sulcata-tortoise','box-turtle',
  'hamster','hedgehog','rabbit','guinea-pig','chinchilla','ferret','sugar-glider',
  'budgie','cockatiel','conure','african-grey','lovebird','canary','cockatoo',
  'labrador','golden-retriever','german-shepherd','french-bulldog','border-collie','siberian-husky',
  'domestic-shorthair','maine-coon','siamese','ragdoll','bengal','persian',
  'tarantula','praying-mantis','millipede','hissing-cockroach','stick-insect','emperor-scorpion',
  'jumping-spider','hermit-crab',
  'pacman-frog','axolotl','whites-tree-frog','fire-bellied-toad','tiger-salamander',
  'betta-fish','goldfish','koi','guppy','angelfish','corydoras-catfish','neon-tetra','oscar',
];

// All care guide IDs (mirrors guidesExtended.js + dogCatGuides.js)
const GUIDE_IDS = [
  'crested-gecko','leopard-gecko','gargoyle-gecko','mourning-gecko','hognose-snake',
  'chameleon','veiled-chameleon','ball-python','bearded-dragon','blue-tongue-skink','corn-snake',
  'ackie-monitor','boa-constrictor','tegu','leaf-tailed-gecko','red-eared-slider',
  'hamster','rabbit','hedgehog','guinea-pig','chinchilla','sugar-glider','african-grey',
  'budgie','lovebird','tokay-gecko','african-fat-tail','uromastyx','savannah-monitor',
  'green-anole','california-kingsnake','milk-snake','russian-tortoise','sulcata-tortoise',
  'box-turtle','ferret','tarantula','praying-mantis','millipede','emperor-scorpion',
  'hissing-cockroach','stick-insect','jumping-spider','hermit-crab','whites-tree-frog','pacman-frog','fire-bellied-toad',
  'axolotl','tiger-salamander','cockatiel','conure','canary','cockatoo',
  'dog-universal','dog-small-breed','dog-medium-breed','dog-large-breed','dog-labrador',
  'dog-golden-retriever','dog-german-shepherd','dog-french-bulldog','dog-border-collie',
  'dog-siberian-husky','cat-universal','cat-domestic-shorthair','cat-maine-coon',
  'cat-siamese','cat-ragdoll','cat-bengal','cat-persian',
  'betta-fish','goldfish','koi','guppy','angelfish','corydoras-catfish','neon-tetra','oscar',
];

// Static routes - must match App.jsx routes. Excludes only the couple of
// routes with no stable default to render (e.g. /donate/success, /donate/cancel
// depend on Stripe redirect query params) - see the "no SPA-fallback" comment
// in public/_redirects for what happens to those at request time. /pack is
// noindex,follow but IS included: without a prerendered file, Cloudflare falls
// through to a 404 for it, and a stale cached copy of that fallback (from
// before this file's SPA-fallback rules were tightened up) kept getting served
// with 200 status and long-dead JS/CSS hashes - see the Ahrefs "broken JS/CSS"
// errors this fixed. Prerendering it gives it the same reliable per-deploy
// static file every other route gets, sidestepping that whole failure mode.
// Generated by scripts/generate-beastlypedia-index.js earlier in the build
// chain, rather than hand-mirrored like the encyclopedia and guide lists above.
// Beastlypedia is going from 1 entry to 15, and a hand-copied list would drift
// silently: the page would still render for a visitor while never getting
// prerendered or listed in the sitemap.
// await readFile, not fs.readFileSync: this file only imports fs/promises, so
// there is no `fs` binding here and the sync call threw at module load, taking
// the whole prerender step (and therefore `npm run build`) down with it.
const BEASTLYPEDIA = JSON.parse(
  await readFile('src/lib/generated/beastlypedia-index.json', 'utf8')
);

// Every fact gets its own URL, because every fact card and modal offers a Share
// button that produces one. Without a file at that path Cloudflare had nothing
// to serve, fell through to 404.html, and the SPA re-routed from there: a real
// 404 status on a link people are actively sharing, and a visible flash of the
// 404 page before the fact appeared.
//
// A wildcard 200 rewrite in _redirects is NOT the fix. See the long note at the
// bottom of public/_redirects: Pages applies those rules before checking for a
// matching static asset, so an earlier "/guides/* / 200" style rule silently
// served the homepage HTML in place of dozens of already-prerendered pages and
// broke canonical and og tags sitewide.
//
// These pages are noindex,follow already (Facts.jsx sets that whenever a fact
// is deep-linked), so prerendering them adds no thin duplicate content and they
// stay out of the sitemap. What it does add is a real 200 and, because social
// crawlers do not run JS, the per-fact og:image that Facts.jsx has always
// computed but never got to emit into a static file.
// Not prerendered any more. scripts/generate-fact-pages.mjs writes these
// straight from the built shell with each fact's head tags stamped in, which
// gives the two things that actually mattered (a real 200 instead of a 404, and
// an og:image social crawlers can see without running JS) for none of the cost.
// They were 281 of 964 routes and the most expendable third of the prerender:
// every one is noindex,follow, so no body ever needed to be static.
//
// That step runs between `vite build` and this one - see package.json.

const STATIC_ROUTES = [
  '/',
  '/facts',
  '/blog',
  '/encyclopedia',
  '/beastlypedia',
  '/guides',
  '/gear',
  '/pack',
  '/quiz/personality',
  '/quiz/trivia',
  '/quiz/knowledge',
  '/about',
  '/contact',
  '/glossary',
  '/animal-facts',
  '/fact-files',
  '/gallery',
  '/categories',
  '/search',
  '/donate',
  '/terms',
  '/privacy',
  ...ENCYCLOPEDIA_CATEGORIES.map(s => `/encyclopedia/category/${s}`),
  ...ENCYCLOPEDIA_CATEGORIES.map(s => `/guides/category/${s}`),
  ...FACT_CATEGORIES.map(s => `/facts/category/${s}`),
  ...GEAR_PET_TYPES.map(s => `/gear/category/${s}`),
  ...ENCYCLOPEDIA_ANIMAL_IDS.map(id => `/encyclopedia/animal/${id}`),
  ...BEASTLYPEDIA.groupSlugs.map(s => `/beastlypedia/group/${s}`),
  ...BEASTLYPEDIA.ids.map(id => `/beastlypedia/${id}`),
  ...GUIDE_IDS.map(id => `/guides/${id}`),
  '/exotic-pet-laws',
  ...LEGAL_ANIMAL_IDS.map(id => `/exotic-pet-laws/${id}`),
  '/care-packages',
  '/care-packages/store',
  '/care-packages/why-we-exist',
  '/care-packages/faq',
];

// Per-attempt deadlines, escalating. A flat 45s was the single biggest cost in
// the build that hit Cloudflare's 20-minute limit: of 7,388 worker-seconds,
// about 3,250 (44%) were spent waiting out timeouts. 49 routes timed out once
// and then passed on the retry, so most of that was a contention blip being
// waited out at full price, and 4 routes burned 225s each failing five times.
//
// Failing the first attempt fast and escalating gets the retry (which usually
// works) started sooner, while still leaving a generous ceiling for pages that
// are genuinely slow rather than merely unlucky.
// Two classes of page, an order of magnitude apart in cost, so one deadline
// cannot serve both. Leaf pages (a single post, fact, beastfile or guide) render
// in well under a second locally; the listing pages render the entire post or
// fact collection and are the ones that time out.
//
// Giving leaves a tight first deadline gets a retry started sooner when the
// runner blips. Giving listings a tight one just guarantees a wasted attempt,
// which is what measuring showed: at 20s the big listings failed attempt 1 on
// every run, and even at 30s several still did.
const LEAF_PATTERNS = [
  /^\/blog\/[^/]+$/, /^\/facts\/[^/]+$/, /^\/beastlypedia\/[^/]+$/,
  /^\/guides\/[^/]+$/, /^\/encyclopedia\/animal\/[^/]+$/, /^\/chronicles\/[^/]+(\/\d+)?$/,
];
const isLeaf = (route) =>
  LEAF_PATTERNS.some(p => p.test(route)) &&
  !/^\/(blog|facts|guides|encyclopedia|gear)\/category\//.test(route);

// Deliberately generous. Tightening these looked attractive (a failed attempt
// is pure waste) but could not be measured honestly: identical runs of the same
// 36 routes on this machine came in anywhere between 12s and 53s depending on
// background load, and every "improvement" from a shorter deadline was inside
// that noise. Cloudflare's runner is ~5x slower per route again, so a deadline
// tuned to a quiet local machine would fail there constantly.
//
// The speedup therefore comes from the structural fixes (page reuse, dropping
// networkidle0, the shared queue, spacing the heavy pages) rather than from
// racing the clock. ROUTE_BUDGET_MS below caps the damage a hopeless route can
// do, and the global budget in main() is what actually guarantees the build
// finishes.
const LEAF_TIMEOUTS_MS = [45000, 60000, 60000, 60000, 60000];
const HEAVY_TIMEOUTS_MS = [60000, 75000, 90000, 90000, 90000];
const timeoutsFor = (route) => (isLeaf(route) ? LEAF_TIMEOUTS_MS : HEAVY_TIMEOUTS_MS);

// Hard ceiling on everything one route may consume across all its attempts.
// Without it a hopeless route costs the sum of every timeout above and blocks
// its whole bucket while doing it.
//
// 200s, raised from 120s once the 275 fact routes moved off this step and freed
// roughly 3 minutes of budget. At 120s a heavy route got exactly two 60s
// attempts; every full run since has shelled about two pages, always different
// ones, which is contention rather than anything wrong with those pages. They
// used to be expendable noindex facts and are now encyclopedia and beastfile
// pages that do get indexed, so buying them a third attempt is worth some of
// the reclaimed time.
const ROUTE_BUDGET_MS = 200000;

// networkidle0 requires 500ms with zero in-flight connections. This app loads
// its route chunk, then that chunk's lazy imports, in waves, so the idle window
// keeps resetting and the wait routinely costs seconds per route on top of the
// real work. 'load' fires once the initial document's subresources are done and
// lets the waitForFunction below do the actual gating, which is what decides
// whether the capture is safe anyway.
//
// Overridable because this is the setting most likely to need backing out if a
// capture ever turns up incomplete.
const WAIT_UNTIL = process.env.PRERENDER_WAIT_UNTIL || 'load';

async function renderRoute(page, route, timeoutMs) {
  const url = `${BASE_URL}${route}`;
  await page.goto(url, { waitUntil: WAIT_UNTIL, timeout: timeoutMs });

  // networkidle0 fires when the JS chunk downloads, but react-helmet-async
  // may not have applied this route's <head> yet. Don't capture until the
  // canonical equals this route's production URL and a meta description is
  // present (noindex pages are exempt - they opt out of SEO tags). Every
  // route including '/' must pass. A timeout is a hard failure: capturing
  // early ships a generic <head> to production, which is worse than a
  // failed build. Timeouts are retried by renderWorker.
  const expectedCanonical = `https://beastlyfacts.com${route === '/' ? '/' : `${route}/`}`;
  await page.waitForFunction(
    (expected) => {
      const robots = document.querySelector('meta[name="robots"]');
      if (robots && /noindex/i.test(robots.getAttribute('content') || '')) return true;
      // MDX article bodies are lazy-loaded (see mdxPosts.js); the Suspense
      // fallback carries [data-mdx-loading] - don't capture until it's gone,
      // or the prerendered HTML ships without the article text.
      if (document.querySelector('[data-mdx-loading]')) return false;
      const canonical = document.querySelector('link[rel="canonical"]');
      const description = document.querySelector('meta[name="description"]');
      return Boolean(
        canonical && canonical.getAttribute('href') === expected &&
        description && description.getAttribute('content')
      );
    },
    { timeout: timeoutMs },
    expectedCanonical
  );

  // Normalize every inline style attribute to React's own serialization
  // format before capturing HTML. The browser's native cssText format is
  // "key: value; key2: value2;" (space after the colon, trailing
  // semicolon) - but React computes its OWN hydration-comparison string
  // from the style object prop as "key:value;key2:value2" (no spaces, no
  // trailing semicolon). Same value, different text, and React's hydration
  // check is a literal string comparison - confirmed directly (multiple
  // times, on both framer-motion-managed and completely plain <div
  // style={...}> elements) that this mismatches on every single build
  // regardless of the actual value, since normal SSR via react-dom/server
  // doesn't hit this (both sides use React's own serializer) but this app's
  // "server" HTML comes from a real browser's live DOM instead. Rewriting
  // every element's style attribute here, from the parsed CSSStyleDeclaration
  // (not string-splitting cssText, which would break on values containing
  // ";" like url() data URIs), makes the captured HTML byte-for-byte match
  // what a real client's hydration-critical render expects.
  await page.evaluate(() => {
    document.querySelectorAll('[style]').forEach((el) => {
      const style = el.style;
      const parts = [];
      for (let i = 0; i < style.length; i++) {
        const prop = style[i];
        const value = style.getPropertyValue(prop);
        const priority = style.getPropertyPriority(prop);
        parts.push(`${prop}:${value}${priority ? ' !important' : ''}`);
      }
      el.setAttribute('style', parts.join(';'));
    });
  });

  const html = await page.content();

  // Strip <script src> tags that Google Tag Manager's own loader snippet
  // injected while this page was being rendered. page.content() serialises the
  // live DOM, so anything a third-party script appended gets baked into the
  // static file - and index.html still contains the snippet that appends it
  // again at request time. The result is GTM loading twice on every prerendered
  // page (three times on some, where the render settled after more than one
  // injection), which PageSpeed measured as /gtm.js listed repeatedly at 116 KiB
  // each and counted toward "reduce unused JavaScript".
  //
  // Only tags pointing at googletagmanager.com are removed, and only ones with a
  // src, so the inline loader snippet and the <noscript> iframe both survive
  // untouched: GTM still loads exactly once for real visitors, via the snippet
  // that was always meant to do it.
  return (
    html
      .replace(
        /<script\b[^>]*\bsrc="https?:\/\/(?:www\.)?googletagmanager\.com\/[^"]*"[^>]*>\s*<\/script>/gi,
        ''
      )
      // Same class of problem, different injector: Vite's __vitePreload helper
      // appends <link rel="modulepreload"> to the head at runtime every time a
      // dynamic import fires, so page.content() bakes the whole lazily-loaded
      // component tree into the static head as eager, High-priority preloads.
      // The homepage built ONE modulepreload and shipped eighteen, pinning
      // 1,077 KB of JS ahead of the document body. On Slow 4G that JS contends
      // with the remaining ~160 KB of HTML, the hero image preload and both
      // font preloads for the same pipe, which is why a prerendered page with
      // inlined critical CSS still measured FCP 3.9s and 2,630 ms of LCP
      // "element render delay" - the hero bytes had arrived at 170 ms and were
      // waiting on the main thread.
      //
      // Vite's own build-time preload is kept: it writes
      // `<link rel="modulepreload" crossorigin href=...>` with no `as`, while
      // the helper sets `link.as = 'script'` on everything it injects. Matching
      // on as="script" removes exactly the runtime-injected set and leaves the
      // entry's real preload alone. These chunks are still fetched normally by
      // the dynamic imports that wanted them, just after first paint instead of
      // ahead of it.
      .replace(/<link\b[^>]*>\s*/gi, (tag) =>
        /\brel="modulepreload"/i.test(tag) && /\bas="script"/i.test(tag) ? '' : tag
      )
  );
}

// A path guaranteed not to match any real route, so it always renders the
// wildcard PageNotFound component - reusing the real app's styling/links
// instead of hand-maintaining a separate static 404 page.
const NOT_FOUND_PROBE_ROUTE = '/__prerender_404_probe__';

async function saveHtml(route, html) {
  const filePath =
    route === '/'
      ? path.join(DIST, 'index.html')
      : path.join(DIST, route.replace(/^\//, ''), 'index.html');

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, html, 'utf-8');
}

// Each tab parses the full JS bundle, so this trades build time against the
// risk that heavy pages (/facts, /encyclopedia, /blog) get CPU-starved, their
// <head> never applies within the wait window, and the build fails. 8 was tried
// and did exactly that, which is why this sat at 4 for a long time.
//
// Still 4, now measured rather than assumed. Timing the same 103-route subset
// (including all three heavy pages) on an 8-core machine, best of several runs
// each: 4 averaged ~91s, 6 averaged ~121s, 8 averaged ~93s. Raising it does not
// buy throughput, because Chromium already runs several processes per tab, so
// four tabs saturate eight cores and extra tabs only add contention.
//
// Left overridable so it can be tuned per machine without a code change, and so
// a Cloudflare build that starts failing can be dialled back from the dashboard
// rather than a commit. MAX_ATTEMPTS below is the safety net either way: a
// starved page is retried, it does not immediately fail the build.
const CONCURRENCY = Number(process.env.PRERENDER_CONCURRENCY) || 4;
const MAX_ATTEMPTS = 5; // retries per route before giving up on it
// Delay before each retry (scaled by attempt number) - gives a transient CPU
// spike on the shared build runner time to clear instead of immediately
// re-contending with the same 3 other buckets that are also mid-render.
const RETRY_BACKOFF_MS = 1500;

// One page per worker, reused across that worker's whole bucket, instead of a
// fresh page per route. Creating a page meant re-enabling request interception
// and re-parsing the entire JS bundle from a cold cache for every one of the
// ~964 routes; navigating an existing page keeps Chromium's compiled-code and
// HTTP caches warm across routes in the same bucket.
//
// The localStorage isolation this replaced a fresh page for is unaffected:
// evaluateOnNewDocument registers once and re-runs on every document, so each
// navigation still starts from cleared storage. A page is only thrown away and
// rebuilt after a failed attempt, where it may be wedged mid-navigation.
async function makePage(browser) {
  const page = await browser.newPage();
      // All 600+ routes render through ONE browser instance sharing the same
      // origin, so localStorage persists across every page.newPage() call in
      // this loop unless explicitly cleared. That didn't matter before, but
      // now that main.jsx defers reading localStorage-backed state (dark
      // mode, visit streak, favorites - see useLocalStorage.js) to an effect
      // instead of a hydration-mismatching lazy useState initializer, that
      // same effect also runs during prerendering (a real browser, not SSR)
      // and writes real values (e.g. recordVisit() incrementing the streak)
      // that would otherwise leak into every subsequently-rendered page,
      // making prerendered output non-deterministic and no longer matching
      // the fresh-visitor baseline hydration needs to reproduce.
      await page.evaluateOnNewDocument(() => {
        try { localStorage.clear(); sessionStorage.clear(); } catch {}
        // Read effects (dark mode/favorites/streak - see useLocalStorage.js)
        // are harmless to run against the now-guaranteed-empty localStorage
        // above, but recordVisit() (FavoritesContext.jsx) unconditionally
        // WRITES a new streak value even on a "no prior visit" start, and
        // its exact timing relative to prerender.mjs's own wait condition
        // (Helmet's meta tags settling) is an unrelated race - capturing
        // mid-write would bake a value into the static HTML that doesn't
        // match the real client's guaranteed-default first render either
        // way. Skipping it during prerendering keeps captured HTML at the
        // same default state hydration will always start from.
        window.__IS_PRERENDER__ = true;
      });
  await page.setRequestInterception(true);
  page.on('request', req => {
    const u = req.url();
    if (u.includes('googletagmanager') || u.includes('google-analytics') ||
        u.includes('pagead') || u.includes('fundingchoices') ||
        u.includes('fonts.googleapis.com') || u.includes('fonts.gstatic.com')) {
      req.abort();
    } else {
      req.continue();
    }
  });
  return page;
}

async function renderWorker(browser, nextRoute, results, deadline) {
  let page = await makePage(browser);
  for (let route = nextRoute(); route; route = nextRoute()) {
    // Out of time: fall back to the plain SPA shell for everything left. The
    // page still returns 200 and still works for a visitor, it just ships
    // without this route's prerendered <head> and body. That is a worse page
    // than a real render and a far better outcome than the whole build being
    // killed at the 20-minute mark, which is what happened on 4 August and took
    // every other route's update down with it.
    if (Date.now() > deadline) {
      await saveHtml(route, results.shell);
      results.shelled.push(route);
      continue;
    }

    const routeStarted = Date.now();
    let lastErr = null;
    let done = false;
    for (let attempt = 1; attempt <= MAX_ATTEMPTS && !done; attempt++) {
      if (attempt > 1) {
        if (Date.now() - routeStarted > ROUTE_BUDGET_MS) break;
        await new Promise(r => setTimeout(r, RETRY_BACKOFF_MS * attempt));
      }
      const timeouts = timeoutsFor(route);
      const timeoutMs = timeouts[Math.min(attempt - 1, timeouts.length - 1)];
      try {
        const html = await renderRoute(page, route, timeoutMs);
        await saveHtml(route, html);
        console.log(`  ✓ ${route}${attempt > 1 ? ` (attempt ${attempt})` : ''}`);
        results.passed++;
        done = true;
      } catch (err) {
        lastErr = err;
        // The page may be wedged mid-navigation after a timeout, so retries get
        // a clean one rather than inheriting whatever state broke this attempt.
        try { await page.close(); } catch {}
        page = await makePage(browser);
      }
    }
    if (!done) {
      console.warn(`  ✗ ${route} - ${lastErr?.message ?? 'route budget exceeded'}`);
      await saveHtml(route, results.shell);
      results.failed++;
    }
  }
  await page.close();
}

async function main() {
  // On Cloudflare Pages, skip prerender for non-production branches (preview deploys).
  // Set CF_PAGES_BRANCH in the Cloudflare Pages env vars, or SKIP_PRERENDER=true to always skip.
  const branch = process.env.CF_PAGES_BRANCH;
  if (process.env.SKIP_PRERENDER === 'true' || (branch && branch !== 'main')) {
    console.log(`Skipping prerender (branch: ${branch || 'unknown'}, SKIP_PRERENDER=${process.env.SKIP_PRERENDER})`);
    process.exit(0);
  }

  console.log('🔍 Discovering dynamic routes from MDX metadata...');
  const mdxMeta = JSON.parse(await readFile(MDX_META_PATH, 'utf-8'));
  const mdxCategoryRoutes = getMdxCategoryRoutes(mdxMeta);
  const mdxRoutes = getMdxRoutes(mdxMeta);
  const chroniclesRoutes = getChroniclesRoutes(mdxMeta);
  const discovered = [...new Set([...STATIC_ROUTES, ...mdxCategoryRoutes, ...mdxRoutes, ...chroniclesRoutes])];

  // Local escape hatch: PRERENDER_ONLY takes a comma-separated list of exact
  // routes so a single page can be re-rendered in seconds instead of waiting
  // out all ~600. Purely for verifying head/markup changes by hand - unset in
  // CI, where the full set always renders.
  const only = process.env.PRERENDER_ONLY?.split(',').map(r => r.trim()).filter(Boolean);
  const selected = only?.length ? discovered.filter(r => only.includes(r)) : discovered;
  if (only?.length) console.log(`⚠️  PRERENDER_ONLY set - rendering ${selected.length} of ${discovered.length} routes`);

  // No priority sort any more. It existed to push the 281 noindex /facts/<slug>
  // routes to the back so the budget would eat those first; they are now
  // generated without a browser by scripts/generate-fact-pages.mjs and never
  // reach this list. What is left is all indexable, with no clearly expendable
  // tier, so ordering is left to the heavy/light interleave below.
  const allRoutes = selected;

  // A safety net for a hung prerender, not a target. It should essentially
  // never fire.
  //
  // It was 13 minutes, set from Cloudflare's documented 20 minute build
  // timeout. That was wrong in practice: the 4 August build that got killed had
  // been running `npm run build` for 34 minutes at the point of termination
  // (14:51:59 to 15:26:02 in its log), so this project is not being cut off at
  // 20. The docs still say 20 for every plan, so treat ~34 as observed rather
  // than promised, and keep real margin under it.
  //
  // 25 leaves roughly 4 minutes of headroom under that observed cutoff once the
  // ~4.5 minutes of install, thumbnails, vite build, sitemap and critical CSS
  // are counted, and is more than three times what the step actually uses:
  // after the fact routes moved off it, a full run is 455s. The old 13 was
  // tight enough to shell 39 pages on a build that had time to spare.
  const BUDGET_MS = Number(process.env.PRERENDER_BUDGET_MS) || 25 * 60 * 1000;
  const deadline = Date.now() + BUDGET_MS;

  console.log(`📄 Prerendering ${allRoutes.length} routes with concurrency ${CONCURRENCY} on ${cpus().length} cpu(s), ${Math.round(BUDGET_MS / 60000)} min budget...`);

  const server = await preview({ preview: { port: PORT, open: false } });
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });

  // Read before rendering anything: route '/' writes over dist/index.html, so
  // after the first worker touches it this is no longer the untouched shell.
  //
  // This assumes dist came straight from `vite build`, which is guaranteed in
  // the build chain where the two run back to back. Re-running prerender by
  // hand over an already-prerendered dist would pick up the rendered homepage
  // instead, so the fallback would carry the homepage's head. Only matters if
  // the budget actually runs out during such a re-run.
  const shell = await readFile(path.join(DIST, 'index.html'), 'utf-8');

  // A shared queue, not CONCURRENCY fixed buckets. Static bucketing gave every
  // worker a fixed slice up front, so a worker that drew slow routes ground on
  // while others sat idle, and nothing could rebalance. Workers now pull the
  // next route whenever they free up.
  //
  // Order matters as much as the queue. The heavy listing pages are adjacent in
  // the route array, so round-robin bucketing handed one to all four workers at
  // the same moment and they starved each other. That is what the retries in
  // local runs were: /facts, /blog, /beastlypedia and /encyclopedia all
  // rendering at once. Spacing them evenly through the light routes keeps at
  // most one in flight at a time.
  const heavy = allRoutes.filter(r => !isLeaf(r));
  const light = allRoutes.filter(r => isLeaf(r));
  const stride = heavy.length ? Math.max(1, Math.floor(light.length / heavy.length)) : 0;
  const queue = [];
  let h = 0;
  for (let i = 0; i < light.length; i++) {
    if (stride && i % stride === 0 && h < heavy.length) queue.push(heavy[h++]);
    queue.push(light[i]);
  }
  while (h < heavy.length) queue.push(heavy[h++]);

  const results = { passed: 0, failed: 0, shelled: [], shell };
  const startedAt = Date.now();
  let cursor = 0;
  const nextRoute = () => queue[cursor++];
  await Promise.all(
    Array.from({ length: CONCURRENCY }, () => renderWorker(browser, nextRoute, results, deadline))
  );
  console.log(`\n⏱️  Rendered in ${Math.round((Date.now() - startedAt) / 1000)}s`);

  // Cloudflare Pages serves a literal 404.html (with a real 404 status) for
  // any request that doesn't match a static asset or an explicit _redirects
  // rule. Generate it from the actual app instead of hand-writing a separate
  // page, so it always matches the live PageNotFound component/styling.
  try {
    const page = await makePage(browser);
    const html = await renderRoute(page, NOT_FOUND_PROBE_ROUTE, HEAVY_TIMEOUTS_MS.at(-1));
    await writeFile(path.join(DIST, '404.html'), html, 'utf-8');
    await page.close();
    console.log('  ✓ 404.html');
  } catch (err) {
    console.warn(`  ✗ 404.html - ${err.message}`);
    results.failed++;
  }

  await browser.close();
  server.httpServer.close();

  console.log(
    `\n🎉 Prerender complete: ${results.passed} succeeded, ${results.failed} failed` +
    `${results.shelled.length ? `, ${results.shelled.length} shipped as SPA shell (out of time)` : ''}.`
  );

  // Never let this pass silently. A shelled route looks fine to a visitor and
  // is invisible in the deploy, so without a loud log the budget could start
  // eating pages every build and nobody would notice until traffic moved.
  if (results.shelled.length) {
    console.warn(
      `⚠️  Ran out of the ${Math.round(BUDGET_MS / 60000)} min prerender budget with ${results.shelled.length} route(s) left. ` +
      `They were written as the plain SPA shell so they still return 200, but they carry no prerendered head or body.`
    );
    console.warn(`   First few: ${results.shelled.slice(0, 5).join(', ')}`);
    console.warn('   Fix by raising PRERENDER_BUDGET_MS if the 20 min Cloudflare limit allows, or by cutting route count.');
  }

  // A route that fails prerendering doesn't 404 - it just falls back to the
  // plain client-rendered SPA shell (see the "no SPA-fallback" comment on
  // STATIC_ROUTES for the routes that don't even get that). That's a worse
  // outcome for that one page's SEO, but failing the entire build over 1-2
  // flaky routes blocks every OTHER page's update too, on a shared/contended
  // build runner where isolated timeouts are expected occasionally even
  // after 5 retries. Only hard-fail when failures are widespread enough to
  // suggest a real, systemic problem worth blocking the deploy over.
  // Proportional, with a floor. A flat 3 was set when this rendered ~600 routes
  // and a failure meant no file at all; there are now 964 and a failed route
  // gets the SPA shell written for it, so it still returns 200 and still works.
  // The 4 August build had exactly 4 contention timeouts, which under the old
  // flat threshold would have failed the deploy on top of the timeout that
  // actually killed it. 1% is still low enough to catch anything systemic.
  const FAILURE_THRESHOLD = Math.max(5, Math.ceil(allRoutes.length * 0.01));
  if (results.failed > FAILURE_THRESHOLD) {
    console.error(`❌ ${results.failed} routes failed prerendering (threshold: ${FAILURE_THRESHOLD}) - failing build.`);
    process.exit(1);
  }
  if (results.failed > 0) {
    console.warn(`⚠️  ${results.failed} route(s) failed prerendering but under the threshold - deploying anyway. Affected routes will serve client-rendered until fixed.`);
  }
}

main().catch(err => {
  console.error('❌ Prerender script crashed:', err);
  process.exit(1);
});
