// schemaTypes/product.js
import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'product',
  title: 'Gear Product (synced)',
  type: 'document',
  // Generated by scripts/sync-gear-to-sanity.js from src/lib/data/affiliateProducts.js,
  // which stays the master list - fields here are read-only in Studio because
  // edits made directly here get overwritten the next time that script runs.
  // Reference one from a Product Recommendation block instead of retyping a
  // product's name/link/image every time it's mentioned in a post.
  fields: [
    defineField({
      name: 'slug',
      title: 'Slug (matches affiliateProducts.js)',
      type: 'string',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'productName',
      title: 'Product Name',
      type: 'string',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      readOnly: true,
    }),
    defineField({
      name: 'retailer',
      title: 'Retailer',
      type: 'string',
      readOnly: true,
    }),
    defineField({
      name: 'affiliateUrl',
      title: 'Affiliate URL',
      type: 'url',
      readOnly: true,
    }),
    defineField({
      name: 'imageUrl',
      title: 'Image URL',
      description:
        'A hosted image URL, not a Sanity-uploaded asset - these products live as static site assets, not Studio uploads.',
      type: 'url',
      readOnly: true,
    }),
  ],
  preview: {
    select: { title: 'productName', subtitle: 'category' },
  },
})
