import React, { useRef } from 'react';
import { Helmet } from 'react-helmet-async';
import { useLocation, useNavigate, useParams, Link } from 'react-router-dom';
import { motion } from '@/lib/motion-safe';
import { ArrowLeft, BookOpen, ChevronRight } from 'lucide-react';
import { encyclopediaAnimals, difficultyColor } from '@/lib/data/encyclopedia';
import { allGuides } from '@/lib/data/guides';
import { facts } from '@/lib/data/facts';
import { getRelatedFacts } from '@/lib/utils/matchAnimal';
import { truncateDescription } from '@/lib/utils/truncate';
import { mdxPosts } from '@/lib/mdxPosts';
import { RELATED_ARTICLES } from '@/lib/data/relatedArticles';
import SaveButton from '@/components/shared/SaveButton';
import TableOfContents from '@/components/blog/TableOfContents';
import AnimalQuiz from '@/components/encyclopedia/AnimalQuiz';
import AnimalCompare from '@/components/encyclopedia/AnimalCompare';
import { IMAGE_DIMENSIONS } from '@/lib/data/imageDimensions';
import { seriesForSlug, chroniclesPath } from '@/lib/chronicles';
import BeehiivSubscribe from '@/components/blog/BeehiivSubscribe';
// encyclopedia id -> the id the legal map uses, so a profile can link straight
// to its own pre-selected map rather than dropping the reader on the hub and
// making them find the animal again. The two id sets do not always match: every
// cat is cat-<breed> in the guides and plain <breed> in the encyclopedia.
//
// Generated by scripts/generate-legal-summary.mjs rather than derived from
// legalStatus.json here: the full matrix is a 400KB chunk, and importing it to
// count restrictions dragged all of it onto every animal page. This is 2KB.
import LEGAL_BY_ENCYCLOPEDIA_ID from '@/lib/generated/legal-summary.json';

function BioField({ label, value }) {
  return (
    <div className="bg-muted/50 rounded-xl p-3">
      <p className="text-xs font-body font-semibold text-muted-foreground mb-1">{label}</p>
      {value
        ? <p className="text-sm font-body text-foreground">{value}</p>
        : <p className="text-sm font-body text-muted-foreground italic">Coming soon</p>
      }
    </div>
  );
}

export default function EncyclopediaAnimal() {
  const navigate = useNavigate();
  const location = useLocation();
  const { id } = useParams();
  const animal = encyclopediaAnimals.find(a => a.id === id);
  const contentRef = useRef(null);
  const guide = animal?.guideId ? allGuides.find(g => g.id === animal.guideId) : null;
  const legal = animal ? LEGAL_BY_ENCYCLOPEDIA_ID[animal.id] : null;

  const handleBack = () => {
    const returnTo = location.state?.returnTo;
    if (returnTo) {
      navigate(returnTo);
      return;
    }

    if (window.history.length > 1) {
      navigate(-1);
      return;
    }
    navigate('/encyclopedia/');
  };

  if (!animal) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Helmet>
          <title>Animal Not Found | Beastly Facts</title>
          <meta name="robots" content="noindex" />
        </Helmet>
        <div className="text-center">
          <span className="text-4xl block mb-3">🔍</span>
          <h2 className="font-display font-bold text-xl text-foreground mb-2">Animal not found</h2>
          <Link to="/encyclopedia/" className="text-secondary text-sm font-body font-semibold hover:underline">
            Browse the encyclopedia →
          </Link>
        </div>
      </div>
    );
  }

  const relatedFacts = getRelatedFacts(animal.name, facts);
  // Legal guides are pulled out of the deep-dive list and given their own card.
  // Mixed in with husbandry articles they read as one more thing to get round
  // to, when they are the one link on the page that can tell a reader they
  // cannot legally keep the animal at all.
  const allRelatedArticles = (RELATED_ARTICLES[animal.guideId] || []).map(slug => mdxPosts.find(p => p._id === slug)).filter(Boolean);
  const legalArticles = allRelatedArticles.filter(a => a.category === 'Legal');
  const relatedArticles = allRelatedArticles.filter(a => a.category !== 'Legal');
  const diffClass = difficultyColor[animal.difficulty] || 'text-muted-foreground bg-muted';
  const bio = animal.bio || {};
  const ogImage = guide?.image
    ? `https://beastlyfacts.com${guide.image}`
    : 'https://beastlyfacts.com/assets/hero-1200.jpg';
  // og:image:width/height must match the actual image's real size - Helmet
  // has no way to "unset" a tag it doesn't declare, so leaving these fixed
  // at 1200x630 would silently misdeclare every animal photo's real dimensions.
  const ogImageDims = (guide?.image && IMAGE_DIMENSIONS[guide.image]) || { width: 1200, height: 630 };
  const pageTitle = `${animal.name} - Encyclopedia | Beastly Facts`;
  const pageDescription = truncateDescription(bio.overview
    || `Learn about the ${animal.name} (${animal.scientific}) - natural habitat, wild diet, lifespan, size, and conservation status.`);
  const canonicalUrl = `https://beastlyfacts.com/encyclopedia/animal/${animal.id}/`;

  return (
    <div className="min-h-screen">
      <Helmet>
        <title>{pageTitle}</title>
        <meta name="description" content={pageDescription} />
        <link rel="canonical" href={canonicalUrl} />
        <meta property="og:title" content={pageTitle} />
        <meta property="og:description" content={pageDescription} />
        <meta property="og:url" content={canonicalUrl} />
        <meta property="og:type" content="article" />
        <meta property="og:image" content={ogImage} />
        <meta property="og:image:width" content={String(ogImageDims.width)} />
        <meta property="og:image:height" content={String(ogImageDims.height)} />
        <meta property="og:image:alt" content={`${animal.name} - Beastly Facts Encyclopedia`} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={pageTitle} />
        <meta name="twitter:description" content={pageDescription} />
        <meta name="twitter:image" content={ogImage} />
        <script type="application/ld+json">{JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Article",
          "headline": pageTitle,
          "description": pageDescription,
          "image": ogImage,
          "url": canonicalUrl,
          "author": { "@type": "Organization", "name": "Beastly Facts", "url": "https://beastlyfacts.com" },
          "publisher": { "@type": "Organization", "name": "Beastly Facts", "url": "https://beastlyfacts.com" },
          "mainEntityOfPage": { "@type": "WebPage", "@id": canonicalUrl },
        })}</script>
      </Helmet>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 pt-12 pb-16">
        {/* Back */}
        <button
          type="button"
          onClick={handleBack}
          className="inline-flex items-center gap-1.5 text-sm font-body font-semibold text-muted-foreground hover:text-foreground transition-colors p-2 -mx-2 -mt-2 mb-4"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Encyclopedia
        </button>

        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-4">
              <span className="text-5xl">{animal.emoji}</span>
              <div>
                <h1 className="font-display font-bold text-2xl sm:text-3xl text-foreground leading-tight">
                  {animal.name}
                </h1>
                <p className="text-sm text-muted-foreground font-body italic mt-0.5">{animal.scientific}</p>
                <div className="flex items-center gap-2 mt-2">
                  <span className="text-xs font-body font-semibold text-muted-foreground bg-muted px-2.5 py-0.5 rounded-full">
                    {animal.category}
                  </span>
                  <span className={`text-xs font-body font-semibold px-2.5 py-0.5 rounded-full ${diffClass}`}>
                    {`${animal.difficulty} care`}
                  </span>
                </div>
              </div>
            </div>
            <SaveButton
              type="encyclopedia"
              id={animal.id}
              title={animal.name}
              subtitle={animal.category}
              url={`/encyclopedia/animal/${animal.id}/`}
              className="flex-shrink-0"
            />
          </div>
        </motion.div>

        {/* Mobile-only: the sidebar's TOC (below) sits in a column that
            collapses to the bottom of the page once the grid drops to a
            single column - same fix as GuideDetail/Blog. */}
        <div className="lg:hidden mb-6">
          <TableOfContents contentRef={contentRef} watch={animal.id} skipText={animal.name} collapsible />
        </div>

        {/* Two-col layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* ── Main content ── */}
          <div className="lg:col-span-2 space-y-5" ref={contentRef}>

            {/* Hero image */}
            {guide?.image && (
              <div className="rounded-2xl overflow-hidden aspect-video">
                <img
                  src={guide.image}
                  alt={animal.name}
                  className="w-full h-full object-cover"
                  loading="lazy"
                />
              </div>
            )}

            {/* Overview */}
            <div className="bg-card border border-border rounded-2xl p-5">
              <h2 className="font-display font-bold text-base text-foreground mb-3">🌍 Overview</h2>
              {bio.overview
                ? <p className="text-sm font-body text-muted-foreground leading-relaxed">{bio.overview}</p>
                : <p className="text-sm font-body text-muted-foreground italic leading-relaxed">
                    Detailed overview coming soon. We're expanding the encyclopedia one animal at a time - check back!
                  </p>
              }
            </div>

            {/* Bio stats */}
            <div className="bg-card border border-border rounded-2xl p-5">
              <h2 className="font-display font-bold text-base text-foreground mb-4">📋 Quick Facts</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <BioField label="Native Range" value={bio.origin} />
                <BioField label="Natural Habitat" value={bio.habitat} />
                <BioField label="Adult Size" value={bio.adultSize} />
                <BioField label="Wild Diet" value={bio.wildDiet} />
                <BioField label="Wild Lifespan" value={bio.wildLifespan} />
                <BioField label="Conservation Status" value={bio.conservation} />
              </div>
            </div>

            {/* Compare */}
            <AnimalCompare animal={animal} key={`compare-${animal.id}`} />

            {/* Test yourself */}
            <AnimalQuiz animal={animal} key={animal.id} />

            {/* Fun facts from facts page */}
            {relatedFacts.length > 0 && (
              <div className="bg-card border border-border rounded-2xl p-5">
                <h2 className="font-display font-bold text-base text-foreground mb-3">🤩 Fun Facts</h2>
                <div className="space-y-3">
                  {relatedFacts.map(fact => (
                    <div key={fact.id} className="bg-secondary/5 border border-secondary/20 rounded-xl px-4 py-3">
                      <p className="text-xs font-body font-bold text-secondary mb-1">{`${fact.emoji} ${fact.title}`}</p>
                      <p className="text-sm font-body text-foreground leading-relaxed">{fact.fact}</p>
                    </div>
                  ))}
                </div>
                <Link
                  to="/facts/"
                  className="inline-flex items-center gap-1 mt-2 text-xs font-body font-semibold text-secondary hover:underline p-2 -mx-2 -mb-2"
                >
                  Browse all animal facts <ChevronRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            )}
          </div>

          {/* ── Sidebar ── */}
          <div className="space-y-4">

            {/* Hidden below lg: the collapsible instance above the article
                already covers mobile. */}
            <div className="hidden lg:block">
              <TableOfContents contentRef={contentRef} watch={animal.id} skipText={animal.name} />
            </div>

            {/* Guide CTA */}
            {guide && (
              <div className="bg-card border border-border rounded-2xl p-5">
                <p className="text-xs font-body font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                  📖 Care Guide
                </p>
                <Link to={`/guides/${guide.id}/`} state={{ returnTo: location.state?.returnTo || '/encyclopedia/' }} className="group block">
                  <div className="flex items-start gap-3 mb-3">
                    <span className="text-2xl flex-shrink-0">{guide.emoji}</span>
                    <div>
                      <p className="font-body font-bold text-sm text-foreground group-hover:text-secondary transition-colors leading-snug">
                        {guide.name} Care Guide
                      </p>
                      <p className="text-xs text-muted-foreground font-body mt-1 leading-relaxed">{guide.tagline}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-1 text-xs font-body font-semibold text-secondary">
                    View full guide <ChevronRight className="w-3.5 h-3.5" />
                  </div>
                </Link>
              </div>
            )}

            {/* Legal status. Links to this animal's own map page rather than the
                hub, so the map arrives already showing the species the reader
                was looking at. */}
            {legal && (
              <div className="bg-card border border-border rounded-2xl p-5">
                <p className="text-xs font-body font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                  ⚖️ Where it is legal
                </p>
                <Link to={`/exotic-pet-laws/${legal.id}/`} className="group block">
                  <p className="text-xs text-muted-foreground font-body leading-relaxed mb-3">
                    {/* No "the {name}" construction on purpose. Names here run
                        from Bengal to Ball Python, and lowercasing them gave
                        "the bengal" while leaving them gave "the Ball Python". */}
                    {legal.restricted > 0
                      ? `${legal.restricted} US jurisdictions restrict this species, from outright bans to permits. Every one quotes the rule it comes from.`
                      : 'Nothing in the jurisdictions we checked restricts this species, and the map shows what was read to say so.'}
                  </p>
                  <div className="flex items-center gap-1 text-xs font-body font-semibold text-secondary">
                    See the state map <ChevronRight className="w-3.5 h-3.5" />
                  </div>
                </Link>
              </div>
            )}

            {/* The written legal guide, kept next to the map rather than in the
                deep-dive list below, so everything legal for this species sits
                in one place and reads as its own kind of thing. */}
            {legalArticles.length > 0 && (
              <div className="bg-card border border-border rounded-2xl p-5">
                <p className="text-xs font-body font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                  ⚖️ Legal Guide
                </p>
                <div className="space-y-3">
                  {legalArticles.map(article => (
                    <Link key={article._id} to={`/blog/${article.slug.current}/`} className="group block">
                      <p className="text-xs font-body font-bold text-foreground group-hover:text-secondary transition-colors leading-snug">
                        {article.title}
                      </p>
                    </Link>
                  ))}
                </div>
              </div>
            )}

            {/* Newsletter signup */}
            <div className="bg-card border border-border rounded-2xl p-5">
              <h3 className="font-display font-bold text-sm text-foreground mb-1">Subscribe - it's free</h3>
              <p className="text-xs text-muted-foreground font-body mb-4">New animal facts and care guides straight to your inbox. No spam. 🐾</p>
              <BeehiivSubscribe />
            </div>

            {/* Related deep-dive articles */}
            {relatedArticles.length > 0 && (
              <div className="bg-card border border-border rounded-2xl p-5">
                <p className="text-xs font-body font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                  📰 Deep Dive
                </p>
                <div className="space-y-3">
                  {relatedArticles.map(article => (
                    <Link key={article._id} to={`/blog/${article.slug.current}/`} className="group block">
                      <p className="text-xs font-body font-bold text-foreground group-hover:text-secondary transition-colors leading-snug">
                        {(article.emoji ? `${article.emoji} ` : '') + article.title}
                      </p>
                    </Link>
                  ))}
                </div>
              </div>
            )}

            {/* Did you know */}
            {guide?.funFact && (
              <div className="bg-secondary/5 border border-secondary/20 rounded-2xl p-5">
                <p className="text-xs font-body font-bold text-secondary mb-2">🤓 Did You Know?</p>
                <p className="text-sm font-body text-foreground leading-relaxed">{guide.funFact}</p>
              </div>
            )}

            {/* Related short story */}
            {animal.relatedStory && (
              <div className="bg-secondary/5 border border-secondary/20 rounded-2xl p-5">
                <p className="text-xs font-body font-bold text-secondary mb-2">📖 Short Story</p>
                <p className="text-xs text-muted-foreground font-body mb-2">{`There's a whole fiction series about a ${animal.name.toLowerCase()}:`}</p>
                <Link
                  to={seriesForSlug(animal.relatedStory.slug) ? chroniclesPath(seriesForSlug(animal.relatedStory.slug).id) : `/blog/${animal.relatedStory.slug}/`}
                  className="group block"
                >
                  <p className="text-sm font-body font-bold text-foreground group-hover:text-secondary transition-colors leading-snug">
                    {animal.relatedStory.title}
                  </p>
                </Link>
              </div>
            )}

            {/* Explore more */}
            <div className="bg-card border border-border rounded-2xl p-5">
              <p className="text-xs font-body font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                Explore More
              </p>
              <div className="space-y-2">
                <Link
                  to={`/encyclopedia/category/${animal.category.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-')}/`}
                  className="flex items-center gap-2 text-sm font-body font-semibold text-foreground hover:text-secondary transition-colors py-1"
                >
                  <BookOpen className="w-4 h-4 flex-shrink-0" />
                  {`All ${animal.category}`}
                  <ChevronRight className="w-3.5 h-3.5 ml-auto" />
                </Link>
                <Link
                  to="/facts/"
                  className="flex items-center gap-2 text-sm font-body font-semibold text-foreground hover:text-secondary transition-colors py-1"
                >
                  <span className="text-base">🤩</span>
                  Animal Fun Facts
                  <ChevronRight className="w-3.5 h-3.5 ml-auto" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
