import React from 'react';
import { Helmet } from 'react-helmet-async';
import { motion } from '@/lib/motion-safe';

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="font-display font-bold text-xl text-foreground mb-3">{title}</h2>
    <div className="text-sm text-muted-foreground font-body leading-relaxed space-y-3">{children}</div>
  </div>
);

export default function Privacy() {
  return (
    <div className="min-h-screen">
      <Helmet>
        <title>Privacy Policy | Beastly Facts</title>
        <meta name="description" content="Read the Beastly Facts privacy policy to understand how we collect, use, and protect your data when you use our animal facts and care guide website." />
        <link rel="canonical" href="https://beastlyfacts.com/privacy/" />
        <meta name="robots" content="noindex, follow" />
        <meta property="og:image" content="https://beastlyfacts.com/assets/og-default.jpg" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content="https://beastlyfacts.com/assets/og-default.jpg" />
      </Helmet>
      <div className="bg-gradient-to-b from-primary/5 to-transparent pt-12 pb-8 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <span className="text-3xl mb-2 block" role="img" aria-label="Padlock">🔒</span>
            <h1 className="font-display font-bold text-3xl sm:text-4xl text-foreground mb-2">Privacy Policy</h1>
            <p className="text-xs text-muted-foreground font-body">Last updated: September 12, 2026</p>
          </motion.div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 pb-16">
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <div className="text-sm text-muted-foreground font-body leading-relaxed mb-6">
            <p>BeastlyFacts.com ("we," "us," or "our") respects your privacy and is committed to protecting the personal information you share with us. This Privacy Policy outlines our data practices and is subject to our overarching <a href="/terms/" className="text-secondary hover:underline">Terms of Service</a>.</p>
          </div>

          <Section title="1. Information We Collect">
            <p>BeastlyFacts.com collects minimal personal information to operate effectively:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-foreground">Newsletter Data</strong> - email address, collected only when you voluntarily subscribe.</li>
              <li><strong className="text-foreground">Contact Information</strong> - name and message content provided via contact forms.</li>
              <li><strong className="text-foreground">Usage & Analytics Data</strong> - we use Google Analytics to measure traffic. This includes IP addresses, browser information, and on-site interaction events.</li>
              <li><strong className="text-foreground">Additional Analytics</strong> - alongside Google Analytics the Site uses Ahrefs Web Analytics and Cloudflare Web Analytics, both of which measure traffic without setting cookies. Cloudflare's is provided by the host that serves the Site. Both process technical request data such as IP address, referring page and browser type.</li>
              <li><strong className="text-foreground">User-Provided Data</strong> - with your consent, we may securely transmit hashed, first-party data to Google Analytics to improve conversion measurement and audience insights.</li>
              <li><strong className="text-foreground">Comment Data</strong> - if you leave a comment on an article, we store the name you enter, the comment itself, and your email address if you choose to provide one. Your name and comment are shown publicly once approved. Your email address is never displayed publicly and is used only to contact you about your comment if needed.</li>
              <li><strong className="text-foreground">Like & Share Counts</strong> - when you like or share an article we store a random identifier generated by your browser, so the same device is only counted once. This identifier is not linked to your name, email, or any other information about you, and it does not identify you.</li>
              <li><strong className="text-foreground">Purchase Data</strong> - if you buy a care package, Stripe collects your email address at checkout and passes it to us. We store that address alongside a record of what you bought and when, so the purchase can be restored to you later. We do not receive or store your card details at any point.</li>
              <li><strong className="text-foreground">Library Sign-In</strong> - the care package library signs you in with a one time code emailed to the address you purchased with. There is no password and no account is created at checkout. Signing in stores a session token in your browser so you stay signed in, and it lets us show you the purchases recorded against that address and no one else's.</li>
            </ul>
            <p>We do not collect, store, or sell payment card information. Card details are entered on Stripe's own checkout pages and never reach this Site. The email address attached to a purchase is the one exception: Stripe passes it to us so we can deliver the file and restore it to you later, as described above.</p>
          </Section>

          <Section title="2. Cookies & Tracking Technologies">
            <p>This Site uses cookies and similar identifiers to improve your experience:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-foreground">Google Analytics</strong> - used to understand how visitors use the Site. You can opt-out using the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Google Analytics Opt-out Browser Add-on</a>.</li>
              <li><strong className="text-foreground">Advertising</strong> - the Site does not currently serve advertising, and no advertising cookies are set by us or by an ad network. If advertising returns through Google AdSense, third-party vendors including Google would use cookies to serve ads based on your prior visits to this and other sites, and this policy will be updated to say so before that happens.</li>
              <li><strong className="text-foreground">Affiliate Tracking</strong> - third parties, including Amazon, may place cookies on your browser to track referrals and process performance data.</li>
              <li><strong className="text-foreground">Local Storage</strong> - used to save favorite facts and quiz results locally in your browser. These stay on your device and are not sent to us. Local storage also holds the random identifier described above, which records that you have already liked or shared an article.</li>
            </ul>
            <p className="mt-3">Donations are handled entirely on Stripe's own checkout pages, so no payment processing scripts or cookies run on this Site.</p>
            <p className="mt-3">You can choose to opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Google Ads Settings</a>. Alternatively, you can opt out of a third-party vendor's use of cookies for personalized advertising by visiting <a href="https://www.aboutads.info" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">www.aboutads.info</a>.</p>
          </Section>

          <Section title="3. How We Use Your Information">
            <p>Any information collected is used solely to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Send newsletters to subscribers who opt in.</li>
              <li>Respond to contact form inquiries.</li>
              <li>Improve site performance and analytics through enhanced measurement features.</li>
              <li>Process donations and care package purchases securely via Stripe.</li>
              <li>Deliver purchased files, restore them to you through the library, and send you an updated file if a package is revised.</li>
              <li>Serve advertising, if and when the Site carries any. It does not at present.</li>
              <li>Publish approved comments, and count likes and shares on articles.</li>
              <li>Support site operations through affiliate marketing.</li>
            </ul>
            <p>We never sell, rent, or trade your personal information to third parties.</p>
          </Section>

          <Section title="4. Affiliate Marketing Disclosure">
            <p>BeastlyFacts.com participates in affiliate marketing programs, including the Amazon Associates program. As an Amazon Associate, I earn from qualifying purchases. This means we may earn a commission when you click on or make purchases through our affiliate links. These commissions help support the research and content creation on this site. All affiliate links are clearly marked (e.g., "#ad" or "paid link"), and our participation does not influence the integrity of our advice or recommendations.</p>
          </Section>

          <Section title="5. Third-Party Services">
            <p>BeastlyFacts.com uses third-party services, each governed by their own privacy policies:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-foreground">Google</strong> - Analytics now, and AdSense only if advertising returns - <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Ahrefs</strong> - cookieless traffic analytics - <a href="https://ahrefs.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Cloudflare</strong> - hosts and serves the Site, and provides cookieless traffic analytics - <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Supabase</strong> - hosts the database that stores comments, likes, shares and care package purchases, and provides the emailed sign-in code for the library - <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Stripe</strong> - <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Beehiiv</strong> - <a href="https://www.beehiiv.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Policy</a></li>
              <li><strong className="text-foreground">Amazon</strong> - <a href="https://www.amazon.com/privacy" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">Privacy Notice</a></li>
            </ul>
          </Section>

          <Section title="6. Data Retention & Your Rights">
            <p>Newsletter subscribers can unsubscribe at any time using the link in any email. To request access to, correction of, or deletion of your personal data, contact us at <a href="mailto:hello@beastlyfacts.com" className="text-secondary hover:underline">hello@beastlyfacts.com</a>.</p>
            <p>If you are located in the EU/EEA, you have rights under GDPR, including the right to data portability and the right to object to processing.</p>
          </Section>

          <Section title="7. Children's Privacy">
            <p>This Site is not directed at children under 13. We do not knowingly collect personal information from children. If you believe a child has provided personal data, please contact us immediately.</p>
          </Section>

          <Section title="8. Changes to This Policy">
            <p>We may update this Privacy Policy from time to time to reflect changes in our practices. Changes will be posted on this page with an updated date. Continued use of the Site constitutes acceptance of the revised policy.</p>
          </Section>

          <Section title="9. Contact">
            <p>For privacy-related questions, please contact: <a href="mailto:hello@beastlyfacts.com" className="text-secondary hover:underline">hello@beastlyfacts.com</a></p>
          </Section>
        </motion.div>
      </div>
    </div>
  );
}