// Emits docs/LEGAL_MAP_GAPS.md, the per-jurisdiction reading list for the
// cells of legalStatus.json that have never been read.
//
// A cell is a gap when the jurisdiction is in coverage.researched but the
// animal has no entry for it. Per the matrix readme, "legal" already means
// "read and nothing found", so a gap is purely unread, never "no rule".
//
// Ordered by jurisdiction because every hole in a state closes by re-reading
// the sources that state already cites, so one sitting per state clears the
// whole column. Re-run after each sitting: node scripts/legal-gaps.mjs
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const legal = JSON.parse(
  fs.readFileSync(path.join(root, 'src/lib/data/legalStatus.json'), 'utf8'),
);
const outPath = path.join(root, 'docs/LEGAL_MAP_GAPS.md');

const { coverage, jurisdictions, sources, animals } = legal;
const researched = coverage.researched;

const missingByJurisdiction = Object.fromEntries(researched.map((j) => [j, []]));
const missingByAnimal = {};
const sourcesByJurisdiction = Object.fromEntries(researched.map((j) => [j, new Set()]));

for (const [id, a] of Object.entries(animals)) {
  missingByAnimal[id] = [];
  for (const j of researched) {
    const entry = a.jurisdictions[j];
    if (entry) {
      if (entry.sourceId) sourcesByJurisdiction[j].add(entry.sourceId);
    } else {
      missingByJurisdiction[j].push(id);
      missingByAnimal[id].push(j);
    }
  }
}

const total = Object.values(missingByJurisdiction).reduce((n, m) => n + m.length, 0);
const byJ = Object.entries(missingByJurisdiction)
  .filter(([, m]) => m.length)
  .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
const byA = Object.entries(missingByAnimal)
  .filter(([, m]) => m.length)
  .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));

const lines = [];
lines.push('# Legal map gaps');
lines.push('');
lines.push('Generated by `node scripts/legal-gaps.mjs` from src/lib/data/legalStatus.json. Do not edit by hand, re-run the script after each research sitting.');
lines.push('');
lines.push(`Unread cells: **${total}** across ${byJ.length} jurisdictions and ${byA.length} animals. A cell is unread when the jurisdiction is in coverage.researched and the animal has no entry for it. "legal" entries already mean read and nothing found, so every gap below is genuinely unread.`);
lines.push('');
lines.push('Work one jurisdiction per sitting, top to bottom. The sources listed under each state are the ones the matrix already cites for it, so start there and only search beyond them when the cited regulation does not reach the taxonomic group at all.');
lines.push('');
lines.push('## By jurisdiction');
lines.push('');
lines.push('| Code | Jurisdiction | Unread | Sources on file |');
lines.push('|---|---|---|---|');
for (const [j, m] of byJ) {
  lines.push(`| ${j} | ${jurisdictions[j]?.name ?? j} | ${m.length} | ${sourcesByJurisdiction[j].size} |`);
}
lines.push('');
for (const [j, m] of byJ) {
  lines.push(`### ${j} ${jurisdictions[j]?.name ?? ''} (${m.length} unread)`);
  lines.push('');
  lines.push('Sources already cited for this jurisdiction:');
  lines.push('');
  const ids = [...sourcesByJurisdiction[j]].sort();
  if (!ids.length) lines.push('- none on file');
  for (const sid of ids) {
    const s = sources[sid];
    if (!s) {
      lines.push(`- \`${sid}\` (missing from sources block)`);
      continue;
    }
    lines.push(`- \`${sid}\` ${s.title}${s.url ? ` <${s.url}>` : ''}`);
    if (s.note) lines.push(`  ${s.note}`);
  }
  lines.push('');
  lines.push('Animals never read against it:');
  lines.push('');
  for (const id of m) {
    const a = animals[id];
    lines.push(`- [ ] \`${id}\` ${a.name} (${a.scientific})`);
  }
  lines.push('');
}
lines.push('## By animal');
lines.push('');
lines.push('| Animal | Unread | Jurisdictions |');
lines.push('|---|---|---|');
for (const [id, m] of byA) {
  lines.push(`| \`${id}\` | ${m.length} | ${m.join(' ')} |`);
}
lines.push('');

fs.writeFileSync(outPath, `${lines.join('\n')}\n`);
console.log(`legal-gaps: ${total} unread cells, ${byJ.length} jurisdictions, wrote ${path.relative(root, outPath)}`);
