// 16x16 pixel icons for the menu, one per page. Each icon is 16 rows of 16
// palette keys; '.' is empty. Drawn as SVG runs by PixelIcon, so they render
// crisp at any size and come out identical in the prerender and the client.

export const PIXEL_PALETTE = {
  k: '#2a211c', // outline
  w: '#fbf7ef', // paper white
  c: '#efe0bf', // cream
  s: '#a9b1ad', // light gray
  S: '#6d7773', // gray
  t: '#48b08f', // teal
  T: '#2e7d66', // dark teal
  g: '#f0c24b', // gold
  G: '#c08a25', // dark gold
  y: '#ffe36b', // yellow
  o: '#ec8452', // orange
  O: '#b9582f', // dark orange
  r: '#e0514f', // red
  R: '#a3313a', // dark red
  p: '#f6a3b8', // pink
  P: '#d8708c', // dark pink
  b: '#6fb5e6', // blue
  B: '#3b76a8', // dark blue
  n: '#b37a4c', // brown
  N: '#7d4f2e', // dark brown
  l: '#9bd46c', // light green
  L: '#4f9a3c', // green
};

export const PIXEL_ICONS = {
  guides: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kTttttttttttkk.',
    '.kTttttttttttkwk',
    '.kTtwwwwwwwwtkwk',
    '.kTtwsssssswtkwk',
    '.kTtwwwwwwwwtkwk',
    '.kTttttttttttkwk',
    '.kTttggtggtttkwk',
    '.kTtgggggggttkwk',
    '.kTttgggggtttkwk',
    '.kTtttgggttttkwk',
    '.kTttttgtttttkwk',
    '.kkkkkkkkkkkkwwk',
    '..kkkkkkkkkkkkk.',
    '................',
  ],
  articles: [
    '................',
    '.kkkkkkkkkkkk...',
    '.kwwwwwwwwwwkk..',
    '.kwkkkkkkkkwkwk.',
    '.kwwwwwwwwwwkwk.',
    '.kwoooowssswkwk.',
    '.kwoooowwwwwkwk.',
    '.kwoooowssswkwk.',
    '.kwwwwwwwwwwkwk.',
    '.kwsssssssswkwk.',
    '.kwwwwwwwwwwkwk.',
    '.kwsssssswwwkwk.',
    '.kwwwwwwwwwwwwk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  encyclopedia: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kttttttttttk..',
    '..kTwwTTTTTTTk..',
    '..kkkkkkkkkkkk..',
    '.kkkkkkkkkkkkk..',
    '.koooooooooook..',
    '.kOOwwOOOOOOOk..',
    '.kkkkkkkkkkkkk..',
    '...kkkkkkkkkkkk.',
    '...kgggggggggGk.',
    '...kGGwwGGGGGGk.',
    '...kkkkkkkkkkkk.',
    '..kkkkkkkkkkkk..',
    '..kbbbbbbbbbbk..',
    '..kkkkkkkkkkkk..',
  ],
  gear: [
    '................',
    'SSS.............',
    '.SS.............',
    '..kkkkkkkkkkkkk.',
    '..kgggggggggggk.',
    '..kgGgGgGgGgGgk.',
    '...kgggggggggk..',
    '...kgGgGgGgGgk..',
    '....kgggggggk...',
    '....kkkkkkkkk...',
    '.....S......S...',
    '....kSSSSSSSSk..',
    '....kSSk..kSSk..',
    '....kSSk..kSSk..',
    '.....kk....kk...',
    '................',
  ],
  packages: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kccccccggcccck.',
    '.kccccccggcccck.',
    '.kkkkkkkggkkkkk.',
    '.knnnnnnggnnnnk.',
    '.knnnnnnggnnnnk.',
    '.knnnnnnggnnnnk.',
    '.knwwwwnggnnnnk.',
    '.knsssswggnnnnk.',
    '.knnnnnnggnnnnk.',
    '.kNNNNNNGGNNNNk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  facts: [
    '................',
    '........kkkkk...',
    '.......kyyyyk...',
    '......kyyyyk....',
    '.....kyyyyk.....',
    '....kyyyyk......',
    '...kyyyyykkkkk..',
    '..kyyyyyyyyyyk..',
    '..kkkkkyyyyyk...',
    '.....kyyyyyk....',
    '....kyyyyk......',
    '....kyyyk.......',
    '...kyyk.........',
    '...kyk..........',
    '...kk...........',
    '................',
  ],
  factFiles: [
    '................',
    '.kkkkk..........',
    'kgggggkkkkkkkk..',
    'kggggggggggggk..',
    'kgwwwwwwwwwwgk..',
    'kkkkkkkkkkkkkkk.',
    'kGGGGGGGGGGGGGk.',
    'kGGGGGGGkkkkGGk.',
    'kGGGGGGkbbbbkGk.',
    'kGGGGGkbwbbbbkk.',
    'kGGGGGkbbbbbbk..',
    'kGGGGGkbbbbbbk..',
    'kkkkkkkkbbbbkkk.',
    '.........kkkknnk',
    '............knnk',
    '.............kk.',
  ],
  beastlypedia: [
    '................',
    '....kk....kk....',
    '...kook..kook...',
    '...kook..kook...',
    '....kk....kk....',
    '.kk..........kk.',
    'kook..kkkk..kook',
    'kook.koooOk.kook',
    '.kk.koooooOk.kk.',
    '...koooooooOk...',
    '..koooooooooOk..',
    '..koooooooooOk..',
    '..kOoooookoOOk..',
    '...kkkkkk.kkk...',
    '................',
    '................',
  ],
  animalDays: [
    '................',
    '...kk....kk.....',
    '.kkSSkkkkSSkkkk.',
    '.krrrrrrrrrrrrk.',
    '.krrrrrrrrrrrrk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwswswswswswwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwswswkkkswswk.',
    '.kwwwwkook.wwwk.',
    '.kwswskoook.swk.',
    '.kwwwwwkkkwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  gallery: [
    '................',
    '................',
    '.....kkkkk......',
    '....kSSSSSk.....',
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssyyk.',
    '.ksssskkkkssssk.',
    '.ksssk' + 'bbbb' + 'ksssk.',
    '.kssk' + 'bwbbbb' + 'kssk.',
    '.kssk' + 'bbbbbb' + 'kssk.',
    '.kssk' + 'bbbbbB' + 'kssk.',
    '.ksssk' + 'bbBB' + 'ksssk.',
    '.ksssskkkkssssk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  beastle: [
    '................',
    'kkkkkkk..kkkkkkk',
    'ktttttk..kgggggk',
    'ktttttk..kgggggk',
    'ktttttk..kgggggk',
    'ktttttk..kgggggk',
    'kTTTTTk..kGGGGGk',
    'kkkkkkk..kkkkkkk',
    '................',
    'kkkkkkk..kkkkkkk',
    'ksssssk..ktttttk',
    'ksssssk..ktttttk',
    'ksssssk..ktttttk',
    'ksssssk..ktttttk',
    'kSSSSSk..kTTTTTk',
    'kkkkkkk..kkkkkkk',
  ],
  critterKeeper: [
    '................',
    '................',
    '..........kkkk..',
    '.........koooOk.',
    '.....O.O.kowkook',
    '....koOoOoooooOk',
    '...koooooooooook',
    '..kooooooooooOkk',
    'kkkoooooooooOk..',
    'kOOOOOOOOOOOk...',
    '.kkkOOkkkOOk....',
    '....kOOk.kOOk...',
    '....kkkk.kkkk...',
    '................',
    '................',
    '................',
  ],
  quizzes: [
    '................',
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krrwwwwwwrrk..',
    '.krwwwwwwwwwwrk.',
    '.krwwrrrrrrwwrk.',
    'krwwrrwwwwrrwwrk',
    'krwwrwwrrwwrwwrk',
    'krwwrwwrrwwrwwrk',
    'krwwrrwwwwrrwwrk',
    '.krwwrrrrrrwwrk.',
    '.krwwwwwwwwwwrk.',
    '..krrwwwwwwrrk..',
    '...kkrrrrrrkk...',
    '.....kkkkkk.....',
    '................',
  ],
  chronicles: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.knnnnnnnnnnnnNk',
    '.kNNNNNNNNNNNNNk',
    '..kcccccccccck..',
    '..kcssssssssck..',
    '..kcccccccccck..',
    '..kcsssssccccck.',
    '..kcccccccccck..',
    '.knnnnnnnnnnnnNk',
    '.kNNNNNNNNNNNNNk',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  legal: [
    '.......kk.......',
    '......kggk......',
    'kkkkkkkkkkkkkkkk',
    'kggggggggggggggk',
    'kkGkkkkggkkkkGkk',
    '..G...kggk...G..',
    '.G.G..kggk..G.G.',
    'G...G.kggk.G...G',
    'kkkkkkkggkkkkkkk',
    'kgggGkkggkkgggGk',
    '.kGGk.kggk.kGGk.',
    '..kk..kggk..kk..',
    '.....kggggk.....',
    '....kGGGGGGk....',
    '....kkkkkkkk....',
    '................',
  ],
  pack: [
    '................',
    '................',
    '...kkk...kkk....',
    '..krrrk.krrrk...',
    '.krwwrrkrrrrrk..',
    '.krwrrrrrrrrrk..',
    '.krrrrrrrrrrrk..',
    '.krrrrrrrrrrRk..',
    '..krrrrrrrrRk...',
    '...krrrrrrRk....',
    '....krrrrRk.....',
    '.....krrRk......',
    '......kRk.......',
    '.......k........',
    '................',
    '................',
  ],
  search: [
    '................',
    '...kkkkk........',
    '..kbbbbbk.......',
    '.kbwwbbbbk......',
    'kbwbbbbbbbk.....',
    'kbwbbbbbbbk.....',
    'kbbbbbbbbbk.....',
    'kbbbbbbbbBk.....',
    '.kbbbbbbBk......',
    '..kbbbBBkk......',
    '...kkkkknnk.....',
    '.........knnk...',
    '..........knnk..',
    '...........knnk.',
    '............kk..',
    '................',
  ],
  feed: [
    '................',
    '...kkkkkkkkkk...',
    '...kSSSSSSSSk...',
    '...kwwwwwwwwk...',
    '...kwoooooowk...',
    '...kwoooooowk...',
    '...kwoooooowk...',
    '...kwwwwwwwwk...',
    '...kwsssssswk...',
    '...kwwwwwwwwk...',
    '...kwttttttwk...',
    '...kwttttttwk...',
    '...kwwwwwwwwk...',
    '...kSSSkkSSSk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  about: [
    '................',
    '................',
    '......kkkkk.....',
    '..O.kkooooOkk...',
    '.O.koooooooooOk.',
    'O.kooookwoooooOk',
    '.koooookkoooooOk',
    '.koooooooooooOOk',
    '.kooooooooookkk.',
    'koooooooooOOk...',
    'kOoooooooOOk....',
    'kNOOOOOOOOk.....',
    'kNNNNNNNNk......',
    'NkNkNkNkN.......',
    'N.N.N.N.........',
    '................',
  ],
  contact: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kkwwwwwwwwwwkk.',
    '.kwkwwwwwwwwkwk.',
    '.kwwkwwwwwwkwwk.',
    '.kwwwkwwwwkwwwk.',
    '.kwwwwkrrkwwwwk.',
    '.kwwwkrrrrkwwwk.',
    '.kwwkwkrrkwkwwk.',
    '.kwkwwwkkwwwkwk.',
    '.kkwwwwwwwwwwkk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  support: [
    '................',
    '.......kkk......',
    '.......kgk......',
    '...kkkkkkkkkk...',
    '.kkppppppppppk..',
    'kppppppppppppPk.',
    'kpkppppppppppPkk',
    'kppppppppppppppk',
    '.kpppppppppppppk',
    '.kpppppppppppPPk',
    '.kPpppppppppPPk.',
    '..kPPPPPPPPPPk..',
    '..kPPkkkkkkPPk..',
    '..kPPk....kPPk..',
    '..kkkk....kkkk..',
    '................',
  ],
};
